### ISSUE TITLE
Streamango not working for me

### ISSUE THREAD

**Issue by bjgood** [jsergio123/script.module.resolveurl#101]
Hey everyone,
Just wondering if anyone else is having trouble with streamango working. It acts like it wants to connect but kicks out after the busy animation circles for a while. It does this for ever source that I've try.

Have a good one. :).

**Comment by jewbmx** [comment]
Works for me but slow lagged start that almost tricks me into thinking its a fail lol

**Comment by bjgood** [comment]
Yeah. It seems to be working this morning.

Closing issue.

**Comment by jewbmx** [comment]
Ive seen that same kinda issue a few times, its like one play glitches out and gets your whole system blocked lol. Might be able to reset your modem next time and see if it resolves
