### ISSUE TITLE
Premiumize Resolver returning transcoded link for torrent/magnet results

### ISSUE THREAD

**Issue by Tikipeter** [jsergio123/script.module.resolveurl#104]
Currently, when attempting to resolve a torrent/magnet link through ResolveURL, the premiumize_me resolver is returning a transcoded file from Premiumize.me. This means 4K files are being returned in their 720p transcoded state.

'stream_link'  on lines 240 and 243 of premiumize_me.py need to be changed to 'link' to fix this issue. The 'stream_link' returned by Premiumize API is the transcoded file (4K is transcoded to 720p), whereas the 'link' is the full sized file.

Alternately, a setting could be added for the user to choose as to whether the full file or transcoded file is returned.

**Comment by jsergio123** [comment]
see if these 2 commits correct the issue https://github.com/jsergio123/script.module.resolveurl/commit/f8988613ba046ef2a74db19ca4b5ae1c193c3272 & https://github.com/jsergio123/script.module.resolveurl/commit/a9763126a4ac4a7f6f27ada9ce492dfc475a54fc
