### ISSUE TITLE
ResolveURL  version 6.3.22

### ISSUE THREAD

**Issue by eeden003** [jsergio123/script.module.resolveurl#107]
I would like to know if version 6.3.22 is a correct working version, because when I want to update this version, it goes back several versions.
I have not downgraded my versions on several machines, but should I do that and why ?
Thanks.

**Comment by eeden003** [comment]
I would like to know if version 6.3.22 is a correct working version, because when I want to update this version, it goes back several versions.
I have not downgraded my versions on several machines, but should I do that and why ?
Thanks.

**Comment by jewbmx** [comment]
Correct version number is 5.0.28

**Comment by eeden003** [comment]
Thank you very much !
