### ISSUE TITLE
gamovideo and powvideo are broken

### ISSUE THREAD

**Issue by blackghostaddon** [jsergio123/script.module.resolveurl#109]
can you fix  this? please.. 
powvideo change  to use hxxps://povvideo.net/na9qzsk22nx5 (link dead) but use  [ p v v i d e o ]  instead powvideo

**Comment by jewbmx** [comment]
Im not sure if i did it right but you can try this https://github.com/jewbmx/script.module.resolveurl/blob/cca5b2005a2c32ff5c707af52275ea861dff13a3/lib/resolveurl/plugins/powvideo.py

**Comment by jewbmx** [comment]
I found a couple working test sources for this resolver and it went from pow to pov and then craptcha block. Dont know if its a constant but assume the resolver will be broken till they remove it lol.

**Comment by jsergio123** [comment]
my VPN ip's are blocked. I can't access the sites to fix

**Comment by Gujal00** [comment]
The embeds are held behind Google RecaptchaV2 gate. Can't do much
If you pass the craptcha on browser it runs coinminer, nasty

**Comment by Gujal00** [comment]
Gamovideo fixed in https://github.com/jsergio123/script.module.resolveurl/commit/859dcf8cf4bbe420d40fe48fd21aef0f3ed6b3a3
