### ISSUE TITLE
Streamango and Mycloud need updating

### ISSUE THREAD

**Issue by bjgood** [jsergio123/script.module.resolveurl#110]
Hey JSergio, and everyone else.
Well, the title says it all. For the past few days streamango and mycloud just will not resolve when I click on a link. The sites are up for them, so it's not that they're offline. Streamango is one of the good ones (as we know).

Thanks a bunch for any help on this.

Have a good one. :).

P.S.
Watch it be working. Just my luck. ;).

**Comment by jewbmx** [comment]
Mango is good on my end, been looking for mycloud to pop up for me before replyin to ya.

**Comment by bjgood** [comment]
Thanks, Jewbmx. That answers my post. Sorry, JSergio. But, I'll probably be back with the same complaint before too long knowing me. :).

Later...

Closing thread.
