### ISSUE TITLE
broken tune.pk and veoh.com

### ISSUE THREAD

**Issue by cache-sk** [jsergio123/script.module.resolveurl#111]
These two links are working, but resolver can't resolve them:

https://www.veoh.com/watch/v832121506M37tCDR
https://pastebin.com/rfQ679h0

https://tune.pk/video/8165594
https://pastebin.com/28HJGgAG

**Comment by cache-sk** [comment]
fix for veoh here:
https://pastebin.com/um49iL77

**Comment by cache-sk** [comment]
fix for tunepk here
https://pastebin.com/g0xYrmiP

do i need to create pullrequest?

**Comment by jewbmx** [comment]
I just tested both of these for ya and can do a pr in a lil bit too.

**Comment by jsergio123** [comment]
@cache-sk yes, please submit a pull request so I may review and merge the changes. Thank you
