### ISSUE TITLE
verystream not working

### ISSUE THREAD

**Issue by xventil** [jsergio123/script.module.resolveurl#113]
when i try to open a verystream link 

for example - https://verystream.com/e/YfRwdGW2G47/62639.mp4

it dosen´t play, here is the log

11:35:47.039 T:8728   DEBUG: CPlayerGUIInfo::InitCurrentItem(https://verystream.com/gettoken/YfRwdGW2G47~1557570865~194.38.0.0~n2ES6zAp?mime=true|Referer=https%3A%2F%2Fverystream.com%2Fe%2FYfRwdGW2G47&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A61.0%29+Gecko%2F20100101+Firefox%2F61.0)
11:35:47.039 T:8728   DEBUG: CAddonDatabase: SELECT repo.id FROM repo .. took 0 ms
11:35:47.046 T:8728   DEBUG: CAddonDatabase: query  SELECT * FROM addons JOIN addonlinkrepo ON addons.id=addonlinkrepo.idAddon WHERE addonlinkrepo.idRepo IN (1) ORDER BY addons.addonID returned 1164 rows in 7 ms
11:35:47.093 T:8728   DEBUG: CAddonDatabase::GetAddons took 53 ms
11:35:47.099 T:10020   DEBUG: CAnnouncementManager - Announcement: OnChanged from xbmc
11:35:47.099 T:10020   DEBUG: GOT ANNOUNCEMENT, type: 1024, from xbmc, message OnChanged
11:35:47.099 T:10020   DEBUG: CAnnouncementManager - Announcement: OnPlay from xbmc
11:35:47.099 T:10020   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnPlay
11:35:47.200 T:8728   DEBUG: ------ Window Init (DialogBusy.xml) ------
11:35:47.224 T:8728   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
11:36:01.281 T:9908   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
11:36:01.281 T:9908   ERROR: CCurlFile::Open failed with code 0 for https://verystream.com/gettoken/YfRwdGW2G47~1557570865~194.38.0.0~n2ES6zAp?mime=true:
11:36:01.281 T:9908   DEBUG: CFileCache::Open - opening <gettoken/YfRwdGW2G47~1557570865~194.38.0.0~n2ES6zAp> using cache
11:36:01.285 T:9908   DEBUG: CurlFile::Open(0xe5861b0) https://verystream.com/gettoken/YfRwdGW2G47~1557570865~194.38.0.0~n2ES6zAp?mime=true
11:36:08.484 T:8728   DEBUG: ------ Window Init (Pointer.xml) ------
11:36:13.621 T:8728   DEBUG: ------ Window Deinit (Pointer.xml) ------
11:36:15.588 T:9908   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
11:36:15.588 T:9908   ERROR: CCurlFile::Open failed with code 0 for https://verystream.com/gettoken/YfRwdGW2G47~1557570865~194.38.0.0~n2ES6zAp?mime=true:
11:36:15.588 T:9908   ERROR: XFILE::CFileCache::Open - failed to open source <https://verystream.com/gettoken/YfRwdGW2G47~1557570865~194.38.0.0~n2ES6zAp?mime=true|Referer=https%3A%2F%2Fverystream.com%2Fe%2FYfRwdGW2G47&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A61.0%29+Gecko%2F20100101+Firefox%2F61.0>
11:36:15.588 T:9908   ERROR: CVideoPlayer::OpenInputStream - error opening [https://verystream.com/gettoken/YfRwdGW2G47~1557570865~194.38.0.0~n2ES6zAp?mime=true|Referer=https%3A%2F%2Fverystream.com%2Fe%2FYfRwdGW2G47&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A61.0%29+Gecko%2F20100101+Firefox%2F61.0]
11:36:15.588 T:9908  NOTICE: CVideoPlayer::OnExit()
11:36:15.588 T:9908   DEBUG: Thread VideoPlayer 9908 terminating

**Comment by jewbmx** [comment]
I just ran a verystream test and its workin for me on non-porn material

**Comment by Gujal00** [comment]
Dont see an issue resolving verystream embeds

**Comment by jsergio123** [comment]
@xventil your URL resolves fine for me. I'll need a full debug log to investigate further but it seems you're having a DNS or ISP issue. Try again using a VPN.

> 11:36:01.281 T:9908 ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
11:36:01.281 T:9908 ERROR: CCurlFile::Open failed with code 0 for https://verystream.com/gettoken/YfRwdGW2G47~1557570865~194.38.0.0~n2ES6zAp?mime=true:

>
