### ISSUE TITLE
New Host ? Holavid.com

### ISSUE THREAD

**Issue by kylesheila** [jsergio123/script.module.resolveurl#122]
Hello Jsergio. I haven't found any references here to holavid so I assume it is a new host or one no one has done a resolver for. I did try to do one with my limited python skills but I need to learn more apparently. Anyway here is an example link https://www.holavid.com/embed-gwu48jwvs35m.html I looked at the source page and the link directs to this part sources: ["https://s9ycljxvbsi6v4rcvremkjzgh5j33fq4.holavid.com/hls/,wya4r4kprv4awxqxiuin2hfmp6jzhmgjvdqnfp2h63pbe2mwscvjnsunsmfa,.urlset/master.m3u8","https://s9ycljxvbsi6v4rcvremkjzgh5j33fq4.holavid.com/wya4r4kprv4awxqxiuin2hfmp6jzhmgjvdqnfp2h63pbe2mwscvjnsunsmfa/v.mp4"], They do have a cookie/expire at the top. I can get these links to play, sometimes both sometimes only one. Thanks for looking in to it if you can.

**Comment by Twilight0** [comment]
The problem is that their https certificate is invalid and Kodi will refuse to play it.

**Comment by jsergio123** [comment]
@Twilight0 the cert looks valid to me. Which domain/url has the invalid https cert?

**Comment by jsergio123** [comment]
@kylesheila added https://github.com/jsergio123/script.module.resolveurl/commit/0e5c9e75a01b1f65f25e28a609cf294265b7b1a8

**Comment by kylesheila** [comment]
Awesome, thank you
