### ISSUE TITLE
some links are not resolving for xstreamcdn

### ISSUE THREAD

**Issue by pinoytracker** [jsergio123/script.module.resolveurl#124]
Hi Jsergio,
Want to inform that some links are not resolving for xstreamcdn
here's the sample links
https://www.xstreamcdn.com/v/e2rl-f-58yllww-
https://www.xstreamcdn.com/v/w3ygxbn62pjjpk-
Thanks

**Comment by jewbmx** [comment]
Think those ones force you to watch a ad first or atleast the second one just did for me, was like a ghetto redirect
