### ISSUE TITLE
Request fo additional resolver

### ISSUE THREAD

**Issue by pinoytracker** [jsergio123/script.module.resolveurl#130]
Hi Jsergio,
Want to Request for additional resolver if possible !
https://onlystream.tv/e/v18v3ooethog
https://onlystream.tv/e/02cff1ox1tsq

Thanks

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.resolveurl/commit/d96b603927202d4aeaa424fad26d4e2a9d086e63

**Comment by jewbmx** [comment]
Tested and workin good.

**Comment by pinoytracker** [comment]
Thanks jsergio, tested and working
