### ISSUE TITLE
verystream with ipv6

### ISSUE THREAD

**Issue by tonyzzz321** [jsergio123/script.module.resolveurl#135]
When using ipv6 to access verystream, the video link contains colon instead of period. With the current regex '(%s\~[\~.a-zA-Z0-9]+)', the part of the link starting with colon is not captured. Adding colon in the regex '(%s\~[\~.:a-zA-Z0-9]+)' in line 40 in verystream.py fixes this problem.

**Comment by jsergio123** [comment]
can you please share examples of the regexes here http://regex101.com/

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.resolveurl/commit/fa32ff0345fe54363cde6bb8d725c4d3f08531b6
