### ISSUE TITLE
hqq new protected code

### ISSUE THREAD

**Issue by diegofn** [jsergio123/script.module.resolveurl#14]
Hello,

netu (dot) tv improved the embed code using a protected way, same like 

```
<div id="07b02207602203a02204b05704e07307603106e05603206d03804502207d" style="height:450px;width:720px"></div>
<script src="https://hqq.tv/player/script.php?3"></script>
```

Can you help us with a code to decode it, and extract the .vid. I am trying to use the unwise function but it does not work.

Thanks for your effort.

**Comment by Gujal00** [comment]
@diegofn 
It is not new and has been there for a while
Use this function and pass the 'id' to it, also needs json library imported.
`def un(sid):`
`	j = 0`
`	s2 = ''`
`	while j < len(sid):`
`		s2 += '\\u0' + sid[j:(j+3)]`
`		j += 3`
`	jd = json.loads(s2.decode('unicode-escape'))`
`	return jd['v']`

And then build the stream url by hand, which can be passed to ResolveUrl
`https://hqq.watch/player/embed_player.php?vid=%s&autoplay=none'%un(id)`

**Comment by diegofn** [comment]
Waw, It works. Thanks for your help!
