### ISSUE TITLE
gounlimited not resolving

### ISSUE THREAD

**Issue by pinoytracker** [jsergio123/script.module.resolveurl#141]
Hi,
want to inform about the gounlimited, sample link
https://gounlimited.to/embed-vwy0x160iay5.html
https://gounlimited.to/embed-o0qgvu6402xq.html

thanks

**Comment by Gujal00** [comment]
The issue is the ssl certificate issuer used by the site (GlobalSign nv-sa) is not trusted by Kodi.
The existing resolver is working correctly if the certificate is added to Kodi cert store
