### ISSUE TITLE
request for a new resolver if possible

### ISSUE THREAD

**Issue by pinoytracker** [jsergio123/script.module.resolveurl#144]
Hi jsergio,
Is it possible for a new resolver
https://viduplayer.com/embed-0ep2i1nh0p6e.html
https://viduplayer.com/embed-kaoc2levnq9g.html

thanks

**Comment by jewbmx** [comment]
Take the megamp4 resolver and change the domain code out for that sites. Works just fine.

https://gist.github.com/jewbmx/f74b4b614d602d977a496c519b4af6e2#file-viduplayer-py

**Comment by pinoytracker** [comment]
thanks jewbmx, working now
