### ISSUE TITLE
additional server for fembed

### ISSUE THREAD

**Issue by pinoytracker** [jsergio123/script.module.resolveurl#145]
hi jsergio,
can we add additional server for fembed and also add a support for dash in media id
https://www.fembed.com/v/yx933-nzq9l

there.to sample link
https://there.to/v/4dojpkemyo1
https://there.to/v/7zo-rdn02ox
thanks

**Comment by jewbmx** [comment]
If your coding you can just do what i did the other day.
`link = link.replace('femoload.xyz', 'fembed.com')`

Works with there.to also.

**Comment by pinoytracker** [comment]
> If your coding you can just do what i did the other day.
> `link = link.replace('femoload.xyz', 'fembed.com')`
> 
> Works with there.to also.

thanks for the suggestion
