### ISSUE TITLE
new resolver

### ISSUE THREAD

**Issue by pinoytracker** [jsergio123/script.module.resolveurl#147]
Hi jsergio,
is it possible to request for a new resolvers
https://gcloud.live/v/4704yszl-e5gqz7
https://gcloud.live/v/3qo17rngr2o

https://vidcloud.icu/load.php?id=MjcxMDUw
https://vidcloud.icu/load.php?id=MjcxMDQ5

Thanks

**Comment by jewbmx** [comment]
That gcloud one you can do the fembed swap on since its another little proxy/domain of it. And if i recall you can rescrape vidcloud with a find all  file: 'hhh.mp4'  hhh.mp4 being the file lol

**Comment by Gujal00** [comment]
vidcloud.icu is an embedder and not vidcloud.co who is a hoster.
you need to scrape the page further and pull all the embeds, there are 5 on that page which you linked above and all are direct links. Sometimes they do embed other hosters which are resolvable by ResolveURl

**Comment by jewbmx** [comment]
I been using this little code bit to counter the issue till i decide to make a def for the isue lol.
Might look odd in this post but its a easy 1 line.

`url = url.replace('xstreamcdn.com', 'fembed.com').replace('gcloud.live', 'fembed.com').replace('femoload.xyz', 'fembed.com').replace('there.to', 'fembed.com') if '/v/' in url else url`
