### ISSUE TITLE
Rapidvideo, Idtbox, Vidto and Vidtodo not working

### ISSUE THREAD

**Issue by bjgood** [jsergio123/script.module.resolveurl#148]
Hi JSergio,
It looks like rapidvideo, idtbox, vidto, and vidtodo are not working for me. One person I know says they're working for him, but for me, no go on any TV series or Movie.

Could someone check and see if these resolvers are giving working links for you?

With gorillavid apparently down (maybe even gone for good) every resolver counts anymore.

Gujal00, could you take a look also?

Thanks for any help on this.

Have a good one, everybody.

**Comment by bjgood** [comment]
Looks like vidtodo is using cloudflare for its links now.

**Comment by jsergio123** [comment]
I'm working on rapidvideo. It will most likely go to pairing. I'll check the other this week.

**Comment by bjgood** [comment]
Thanks, JSergio. As always, I appreciate the response.

Have a good one, buddy.

**Comment by bjgood** [comment]
Hey JSergio,
Couldn't get rapidvideo going again?

Also, any way to deal with cloudflare in a resolver file? All three domains of vidtodo.py (vidtodo.com, vidtodoo.com, and vidtodu.com) are now behind cloudflare pretty much making them useless.

Have a good one. :).

**Comment by doko-desuka** [comment]
@bjgood to update the vidtodo resolver (for the site as seen on 2019-08-19), someone would need to go through these:

1) To take that updated standalone requests-based CF solver: https://github.com/Arias800/CloudflareScraper/blob/master/CloudflareScraper/__init__.py
2) Port it to ResolveURL to make it use the `/lib/resolveurl/lib/net.py` module. An old version by me is available here, it's a good starting point: https://gist.github.com/doko-desuka/ddf3eb55f557f3c025c610a63c86a920
3) To update the `vidtodo.py` resolver to use that CF solver, as well as JS unpacking**. 

** In fact, that speedvid resolver from the gist link in step no.2 should serve vidtodo as well with very little change, provided steps no.1 and no.2 are done first of course, and using this new pattern for the domains: `pattern = '(?://|\.)((?:vidto(?:doo|do|du))\.(?:com))/(?:embed-)?([0-9a-zA-Z]+)'`

**Comment by doko-desuka** [comment]
Update: it seems the CF challenge exists only for the vidtodo domains. If you replace "vidtodo.com" with "playvidto.com" but keep the rest of the URL the same (media ID) etc., then it leads to a page without the CF challenge.

The .MP4 source is still p,a,c,k,e,d however. You need to use the JSUnpack module for that.

----
TL,DR: take the vidtodo resolver, replace the domain with "playvidto", then find the p,a,c,k,e,d media.

**Comment by doko-desuka** [comment]
Here, updated vidtodo using that different domain (it happens in `get_url()`):

```
"""
    Kodi resolveurl plugin
    Copyright (C) 2019 script.module.resolveurl

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from lib import helpers
from resolveurl.common import Net, RAND_UA
from resolveurl.resolver import ResolveUrl, ResolverError

class VidToDoResolver(ResolveUrl):
    name = 'Vidtodo'
    domains = ['playvidto.com', 'vidtodu.com', 'vidtodo.com', 'vidtodoo.com']
    pattern = '((?:playvidto|vidto(?:du|doo?)).*?)/(?:embed-)?([0-9a-zA-Z]+)'
 
    def __init__(self):
        self.net = Net()
        self.userAgent = RAND_UA
        self.net.set_user_agent(self.userAgent)
        self.desktopHeaders = {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'Upgrade-Insecure-Requests': '1',
            'DNT': '1'
        }
    
    def get_media_url(self, host, media_id):
        r = self.net.http_GET(
            self.get_url(host, media_id), headers=self.desktopHeaders
        )                
        sources = helpers.scrape_sources(
            r.content,
            patterns = ['''(?:file|src)\s*["']?\s*[:=,]?\s*["'](?P<url>[^"']+)(?:[^}>\]]+)["']?\s*label\s*["']?\s*[:=]\s*["']?(?P<label>[^"',]+)'''],
            generic_patterns = False
        )
        if sources:
            kodiHeaders = {
                'User-Agent': self.net.get_user_agent(),
                'Accept': 'video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5',
                'Accept-Language': 'en-US,en;q=0.5',
                'DNT': '1',
                'Cookie': '; '.join(cookie.name+'='+cookie.value for cookie in self.net._cj)
            }
            return helpers.pick_source(sources) + helpers.append_headers(kodiHeaders)
        raise ResolverError('Unable to locate video')
        
    def get_url(self, host, media_id):
        return self._default_get_url(host, media_id, template='https://playvidto.com/{media_id}')

```

**Comment by doko-desuka** [comment]
(Actually ignore that Pastebin link. I edited my comment to have the code be inline, it's better as it needed a few edits.)

**Comment by doko-desuka** [comment]
Did anyone try it, is it working on your end?

**Comment by Gujal00** [comment]
All the related domains seems to have some issue as you can't open them in the browser, gets secure connection failed error

**Comment by Gujal00** [comment]
All vidto domains are now using cflare, including the new vidtoro.com

**Comment by TheGridRepo** [comment]
That sucks.. hope there a workaround

**Comment by Gujal00** [comment]
rapidvideo, vidto and idtbox are defunct

vidtodo is behind cloudflare so cant be done
