### ISSUE TITLE
any way of check or adding these 

### ISSUE THREAD

**Issue by TheGridRepo** [jsergio123/script.module.resolveurl#152]
any scrapers for the following would be much appreciated.... https://www.verystream.xyz/source/E7hcmWJmvZJ , https://www.vidlox.xyz/source/gzg3vzgjxl2l , https://onlystream.xyz/embed/r13-_WMdf9k

having issues playing those links

**Comment by jewbmx** [comment]
Looks like fakes to me. Open each one as the plain main page/domain only and they are all 3 the same 404 page

**Comment by jewbmx** [comment]
Yea you need something like this first to have it redirect the proper link...

import requests
content = requests.get(url).url


If ya wanna limit its use some you could do a  if ".xyz" in url: first lol

**Comment by Gujal00** [comment]
All three are fake embedders and are not genuine hosters
Open the URL without redirect and look in the Location header in the reply and that shows the real hoster embed url. May have to revert the merged changes

**Comment by jsergio123** [comment]
@Gujal00 should I revert these changes?

**Comment by Gujal00** [comment]
yeah, it is better if we revert in the next release
