### ISSUE TITLE
Kissasian.sh

### ISSUE THREAD

**Issue by imurreflection** [jsergio123/script.module.resolveurl#164]
Hi Gujal00 bro, great to see your new add-on. Can you please see the possibility of adding the above mentioned site. This is a wonderful site with amazing collection of rare to find or otherwise latest Japanese, Korean, Asian TV Shows and Movies with multiple quality selection.

**Comment by imurreflection** [comment]
Very sorry to post in this as issues are disabled in your repo.

**Comment by Gujal00** [comment]
Please close the issue, I do not have any new addon to target asian stuff nor interested in creating one
