### ISSUE TITLE
Streamango -- asking for pairing

### ISSUE THREAD

**Issue by pinoytracker** [jsergio123/script.module.resolveurl#171]
Just want to inform, asking for a pairing.
This link was error in conversion, but in resolver its asking for a pairing
https://streamango.com/embed/etobkbcbdbflntlk/

**Comment by Gujal00** [comment]
Yes, the resolver asks you to pair before opening the page.
The Link error will be seen once the page is opened and notification shown

**Comment by Gujal00** [comment]
Videohoster shutdown
