### ISSUE TITLE
playerdrive.com - Add To resolveurl

### ISSUE THREAD

**Issue by xventil** [jsergio123/script.module.resolveurl#177]
hello, is it possible to add support to playerdrive.com ?

sample links;

https://playerdrive.com//player/156204

https://playerdrive.com//player/155794

Thanks in advance

**Comment by Twilight0** [comment]
This is a web-based wrapper for google video.

**Comment by xventil** [comment]
sorry for the stupid question, but.. what does that mean in practical cases?

**Comment by Twilight0** [comment]
It means that they do not host the videos themselves but rather wraps them around a javascript-based resolver for their own benefit (have subscription plans etc.). They leech google cdn resources. In the end I wouldn't be willing to do a resolver for that, perhaps someone else might.

**Comment by xventil** [comment]
ok, thank you for the explanation.

Going to close the issue.
