### ISSUE TITLE
Please add this host, https://gofile.io.

### ISSUE THREAD

**Issue by luhanmcs** [jsergio123/script.module.resolveurl#18]
Thanks and advance.

**Comment by bugatsinho** [comment]
plz provide a link

**Comment by luhanmcs** [comment]
https://gofile.io/?c=v8bPsb
https://gofile.io/?c=BMHgkv
https://gofile.io/?c=2vHYiK
https://github.com/azzy9/script.module.urlresolver/blob/3b926f4476527f10d1b43cb880365541bdff104b/lib/urlresolver/plugins/gofile.py

**Comment by jsergio123** [comment]
@azzy9 please submit your plugin so I dont have to take credit for it. Thanks

**Comment by azzy9** [comment]
@jsergio123 If you you wish to port any of my contributions from urlresolver, then I have no problems with that. It won't be 'till later that I will get a chance to look at doing it due to work.

**Comment by azzy9** [comment]
@jsergio123 I have made PR #20

**Comment by luhanmcs** [comment]
Teamwork, that's the way things should be, and everyone wins from it. Thanks.
