### ISSUE TITLE
Vivo

### ISSUE THREAD

**Issue by DWH-WFC** [jsergio123/script.module.resolveurl#185]
Vivo, Vidlox, Jetload, Gounlimited Resolve URL not function

**Comment by kasi45** [comment]
@DWH-WFC 
hatte ich dir doch schon mal geschrieben - ohne konkrete Beispiele oder ein Debug kann dir nach so einer pauschalen Aussage nicht geholfen werden.

Im übrigen kann ich erst mal nur bestätigen ' VIVO not resolving' !

Andere von dir genannten Resolver z.B. Vidoza, Gounlimited  liefern ein Resultat! Zumindest bei mir!

**Comment by DWH-WFC** [comment]
was nutzt du denn für ein resolver?
Es hieß das der xStream Resolver die module von jsergio nutzt also hab ich das hier gepostet.
Verstehe dein Problem nicht hab auf s.to geschaut da da die Links funktionieren aber in xStream nicht hab ich dies gemeldet.
