### ISSUE TITLE
Are possible Mod this addon for accept your "ResolveUrl" too.??

### ISSUE THREAD

**Issue by luhanmcs** [jsergio123/script.module.resolveurl#19]
https://github.com/kodil/kodil/tree/master/repo/plugin.video.link__tester
This addons work with "UrlResolver" is possible work with "ResolveUrl" too? Run both at the same time?
I use "plugin.video.link__tester" for stream files from "strm" files.
Sample. "plugin://plugin.video.link__tester/?link=url_supported_hosts&amp;mode=play_link"
Thanks and advance.

**Comment by bugatsinho** [comment]
fork the addon and import resolveurl as urlresolver!

**Comment by luhanmcs** [comment]
I made the fork, but it still gives some errors, they must be errors of the addon itself, because the scrapers work well in other addons. Thanks.
