### ISSUE TITLE
Google links

### ISSUE THREAD

**Issue by poortuga** [jsergio123/script.module.resolveurl#190]
Hi
It's possible to run this kind of links on kodi?
'https://doc-0k-a8-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/(*+)I3Y_-9aeW_8?e=download'
Thanks

**Comment by Twilight0** [comment]
https://regex101.com/r/e7ZOgn/1
So yes

**Comment by poortuga** [comment]
Thanks for the reply
Forget about the regex,what about this one ?
https://doc-0s-80-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/20qd4s500hso4se3me59314iaabiia2v/1569520800000/07582993918661853032/*/19cwsXuPNEVzN9ZuaYcLYhNr-aMaCxRHs?e=download

Do this link need to be resolved before send it to the player?
Thanks

**Comment by Twilight0** [comment]
The second one works as well, but you are not stating your exact issue. I am getting 403 error, you 're probably in the need of the google drive addon also authorized, then try to play it via resolveurl.

**Comment by poortuga** [comment]
I can't make this run on kodi

ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
14:58:53.200 T:10300   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
14:58:53.201 T:7932  NOTICE: Creating InputStream
14:58:53.685 T:7932  NOTICE: Creating Demuxer
14:58:54.147 T:7932   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, https://doc-08-0c-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/d2894ug35fppptq34r95j7ise13st09q/1569700800000/09475561101239502681/*/12y92TO66X3UrHsz06KGUxfaWK6nPrZpd?e=download
14:58:54.148 T:7932   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
14:58:54.148 T:7932  NOTICE: CVideoPlayer::OnExit()

Any Help would be grateful.
Thanks
