### ISSUE TITLE
dailynotion.me

### ISSUE THREAD

**Issue by rrosajp** [jsergio123/script.module.resolveurl#193]
hi @Gujal00 
can u fix this pl.
it give this error:

[dailynotion.log](https://github.com/jsergio123/script.module.resolveurl/files/3693699/dailynotion.log)

`DEBUG: ResolveURL: Resolving using dailynotion.me plugin
DEBUG: ResolveURL: Scrape sources |["']?\s*(?:file|src)\s*["']?\s*[:=,]?\s*["'](?P<url>[^"']+)(?:[^}>\]]+)["']?\s*label\s*["']?\s*[:=]\s*["']?(?P<label>[^"',]+)| found |[(u'360P', u'https://orbit.dailynotion.me/link/Fh7eoxukZeyxAqm/360/83c937bac2dc4cf2c4d359b0840a2f04/477f23a9f0320d85e46218fb877362a2/'), (u'720P', u'https://orbit.dailynotion.me/link/Fh7eoxukZeyxAqm/720/83c937bac2dc4cf2c4d359b0840a2f04/cc17a2f318f881d677e1e3f2291a24aa/')]|
DEBUG: ResolveURL: [(u'720P', u'https://orbit.dailynotion.me/link/Fh7eoxukZeyxAqm/720/83c937bac2dc4cf2c4d359b0840a2f04/cc17a2f318f881d677e1e3f2291a24aa/'), (u'360P', u'https://orbit.dailynotion.me/link/Fh7eoxukZeyxAqm/360/83c937bac2dc4cf2c4d359b0840a2f04/477f23a9f0320d85e46218fb877362a2/')]
DEBUG: ResolveURL: Setting Headers on UrlOpen: {u'Referer': u'http://dailynotion.me/player/Fh7eoxukZeyxAqm/', u'Cookie': u'__cfduid=dd5ceab5fc79d8cc07acaed0e78fd60561570309208; expires=Sun, 04-Oct-20 21:00:08 GMT; path=/; domain=.dailynotion.me; HttpOnly, PHPSESSID=0a92d820ba562214b156e15fdc20a695; path=/', u'User-Agent': u'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134 '}
WARNING: ResolveURL: Stream UrlOpen Failed: Url: https://orbit.dailynotion.me/link/Fh7eoxukZeyxAqm/720/83c937bac2dc4cf2c4d359b0840a2f04/cc17a2f318f881d677e1e3f2291a24aa/|Cookie=__cfduid%3Ddd5ceab5fc79d8cc07acaed0e78fd60561570309208%3B+expires%3DSun%2C+04-Oct-20+21%3A00%3A08+GMT%3B+path%3D%2F%3B+domain%3D.dailynotion.me%3B+HttpOnly%2C+PHPSESSID%3D0a92d820ba562214b156e15fdc20a695%3B+path%3D%2F&Referer=http%3A%2F%2Fdailynotion.me%2Fplayer%2FFh7eoxukZeyxAqm%2F&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F64.0.3282.140+Safari%2F537.36+Edge%2F17.17134+ HTTP Code: 601 Msg: '' (ENCODED)`

**Comment by Gujal00** [comment]
Dailynotion is not working, looks like the site is going through an overhaul. Will take a look when it is settled

**Comment by jsergio123** [comment]
dead host?

**Comment by Gujal00** [comment]
Yep looks like a deadhost

**Comment by azzy9** [comment]
for me, the server seems very hit and miss. when it does load the resolver is able to get a URL and play the video still.
