### ISSUE TITLE
Fastplay.to

### ISSUE THREAD

**Issue by TheGridRepo** [jsergio123/script.module.resolveurl#209]
Just Wondering if there a issue with fastplay.py links not playing for some reason.

**Comment by Gujal00** [comment]
fastplay have recently introduced domain protection, so if the embed link is protected to the particular domain where it is found, then it is not resolvable in resolveurl as currently there is no way to pass referer url along with embed code to ResolveUrl

**Comment by jsergio123** [comment]
@Gujal00 where does the referrer need to be passed? https://github.com/jsergio123/script.module.resolveurl/blob/master/lib/resolveurl/plugins/fastplay.py

**Comment by Gujal00** [comment]
line 42: `r = self.net.http_GET(web_url, headers=self.desktopHeaders)`
that whole desktopheaders looks bogus. It should be a User-Agent and Referer
without the site doing the embed as referer the response to the above call is "this stream is domain protected"
the referer is the site using the embed, so will be different all the time
