### ISSUE TITLE
Vidnode.net

### ISSUE THREAD

**Issue by bjgood** [jsergio123/script.module.resolveurl#211]
Just wondering if someone could take a look at vidnode.py. It doesn't seem to give any working links. It kicks out after it tries to connect.

**Comment by Gujal00** [comment]
Seems to be working correctly, can you be more specific and provide a sample embed? replace http with hxxp when posting here

**Comment by bjgood** [comment]
So, it's working for you? Scan Endeavour Season 6 Episode 1, and choose vidnode.

I can't supply a link because none of them work. Sorry.

**Comment by Gujal00** [comment]
If none of them work, how can resolveurl make them work, Dont understand what you are asking here.
Any embeds working on vidnode site are correctly resolved by SMR

**Comment by dobbelina** [comment]
> 
> 
> Just wondering if someone could take a look at vidnode.py. It doesn't seem to give any working links. It kicks out after it tries to connect.

If Exodus,
Tools=>Cache functions=>clear providers
Tools=>Cache functions=>clear cache
Tools=>Cache functions=>clear Meta Cache
Tools=>UrlResolver Settings=>Reset function cache

script.module.urlresolver just updated, so re-start kodi first to get the update,
then do the above.

**Comment by bjgood** [comment]
> If none of them work, how can resolveurl make them work, Dont understand what you are asking here.
> Any embeds working on vidnode site are correctly resolved by SMR

Thanks for your response. I'm only reporting what I've observed with reference to vidnode. If it's working for you then great. It has worked for me in the past, but not now.

Best regards.
