### ISSUE TITLE
vidnode on exodus and exodus redu

### ISSUE THREAD

**Issue by wicca71** [jsergio123/script.module.resolveurl#214]
since the other day i have had issues watching tv programes and films on kodi, i had lots of links that worked great and now the only links i have are vidnode, the odd one works on some tv series, and nothing out of 9/10 links work on others. Ive re installed kodi 17.6, and re installed kodi etc and there still not working. Im no tech wiz and am disabled, house bound so im a little frustrated at the moment, can anyone please help me. I rely on the tv to keep me sane. or if anyone can suggest an easier way for me. Thank you in advance. 
![IMG-0932](https://user-images.githubusercontent.com/22235396/68285721-b79f4c80-0077-11ea-877d-6143778f597f.JPG) this is what i get and they wont work on many tv shows ive tried

**Comment by wicca71** [comment]
no one can help me then?

**Comment by bjgood** [comment]
I'm having the exact same problem with vidnode. Gujal00 claims they should work. But, they don't.

Thanks for confirming.

**Comment by wicca71** [comment]
I’ve dl 18.4 Kodi and no limits magic, it has exodus r on and now they all
work x

**Comment by bjgood** [comment]
Well....so much for my post.

I always run the latest kodi, and my sources are generally up-to-date. Still no go on vidnode.

Since your issue is now resolved you should close this thread.

Later...

**Comment by Gujal00** [comment]
Addons not getting working links is not a resolveurl issue
