### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by mafiwa2167** [jsergio123/script.module.resolveurl#217]
Is there any work being done towards making the addon Python 3 compatible? This is a blocker for many other addons which depend on resolveurl / urlresolver.

**Comment by Twilight0** [comment]
As far as I am concerned there is no work done yet towards Python 3 support, however there have been talks about it.

**Comment by mafiwa2167** [comment]
@Gujal00 Do you know anything about this?

**Comment by jsergio123** [comment]
Honestly I dont see the point in supporting Python 3. I barely have the time to keep the non-debrid plugins working. @Gujal00 has been a tremendous help with that recently.

Which addons that use SMR support python 3? What benefit other than being able to use Kodi 19 would this serve?

**Comment by Twilight0** [comment]
There probably are a few addons supporting python 3 that utilize SMR, including my very own AliveGR 2.0.0 which release is pending, but the point is Kodi 19 hasn't received an official Alpha version, only nightlies so far, has many bugs waiting to be fixed and there is no real benefit into using it, 18.X has matured and is stable, its binary addons are updated in frequent basis and its great for everyday use.
