### ISSUE TITLE
movpod and daclips not working

### ISSUE THREAD

**Issue by bjgood** [jsergio123/script.module.resolveurl#23]
Hi jsergio,
I don't know on other peoples setup, but on mine both movpod and daclips are not working any longer. Could you please check them out? They are generally my goto links. Hopefully they can be fixed easily.

Thanks a bunch.

A fan,
Bob

**Comment by jsergio123** [comment]
will look into those plugins thanks for the heads up

**Comment by jsergio123** [comment]
@bjgood are you able to play the videos via their websites? The videos dont play for me.

**Comment by bjgood** [comment]
Hi jsergio,
If I go to either site I'm bombarded with popups when I click on a video link. Never could get a video to play.

God, I'd hate to lose them as a source for links. There's so few that are left that provide lower quality links anymore. Gorillavid is about the only one.

Thanks for your efforts, jsergio. Without you I don't know what this community would do. You're a valuable asset. :).

A fan,
Bob

**Comment by Gujal00** [comment]
PR #32 raised with fixes for both resolvers

Actually both embedders point to gorillavid for the final stream url.

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.resolveurl/commit/7385f1a9c7c048c02c426797cecaea60c1582a0a

**Comment by bjgood** [comment]
Thanks, jsergio and Guja. :).

So, daclips and movpod now point to gorillavid for the playback. Wonder if it was that way before daclips and movpod stopped working?

Have a good one. :).
Bob
