### ISSUE TITLE
Resolveurl and NZBs

### ISSUE THREAD

**Issue by JamesJB77** [jsergio123/script.module.resolveurl#236]
Hi Jsergio,

I was in contact with https://orionoid.com/ support and was talking about NZBs, cached NZBs, and the possibility of someone developing a kodi addon to to just support  playing NZBs.  They had the following suggestion.  What are your thoughts on what they said?

"Why not add this feature to ResolveURL, then all addons can use NZBs over debrid. I think this has been lacking in ResolveURL for a very long time. ResolveURL needs code to download torrents that are non-cached, and to download NZBs. They should also provide batch cache lookup functionality - currently many addons do it themselves."

**Comment by solbu** [comment]
In my opinion this belongs in a separate resolve-torrent-url addon.

There are many users who will not for any reason be involved in torrenting.
For one, every torrent downloads means the user downloading is _Also_ uploading, and they don't want to risk being caught in an anti piracy dragnet.

Besides, not everyone that use an addon depending on resolveurl have the diskspace to store a single movie. Many systems are Raspberry devices, with close to no storage space, they use the device to Stream everything they watch.

**Comment by jsergio123** [comment]
@jjred1977 resolveurl currently supports both cached and non-cached torrents/magnets through real-debrid, alldebrid, and premiumize. It doesn't support Usenet. It doesn't search for any content.

As for batch lookup, this needs to be handle via the addon depending on resolveurl as SMR is designed to only resolve one link at a time. A dev can use a threaded workload to do any batch processing.

@solbu seeding/leeching is handle completely through the debrid service. The debrid service will serve the file via HTTP to resolveurl. No uploading or storing is done on the user device end,

**Comment by JamesJB77** [comment]
@jsergio123 Thank you for responding to my comment.  I will pass what you stated on to them.  If you are interested in what they have to say back please leave the thread open and I will post their response to what you said.  I am learning about how Kodi and its parts work together to stream and was introduced to Orion for cached links.  I have heard that only Gaia is only able to play NZB content (or was able to I'm not sure of the status now) or you can place the NZB in premiumize and that will allow it to be able to view via kodi.  There has been talk on the A4K discord of trying to develop an "NZB addon" for those of us who have NZB index subscriptions who want to just play the content through Kodi so I was just trying to find out how to do so with the least amount of work.  Thanks again for you input.

**Comment by jsergio123** [comment]
@jjred1977 I'm always open to adding more ways to reliably stream content especially with many larger free hosts being taken offline.

**Comment by JamesJB77** [comment]
@jsergio123 Orion provided a response back to you.  " jsergio's recommendation about batch lookups is not great. His idea would mean that if you want to check 500 links, you will make 500 request to the debrid API, each request only looking up a single link/hash. This is not only way slower, but puts a heavy load on the debrid servers (especially if many people do it). Instead they should have a 2nd function that allows you to submit a bunch of links/hashes with a SINGLE request. Adding batch lookups should only require a few lines of code. Adding usenet support would require a lot more code."

**Comment by jsergio123** [comment]
Yes I realize that but like I said resolveurl is designed to resolve or validate one link only when passed to it. I plan to keep it that way. Any batch processing for building/filtering lists of sources from another add-on should be handled by that add-on itself. I must stay neutral and can not involve myself in any piracy.

**Comment by JamesJB77** [comment]
I totally get it. If you go down most everything goes down. I followed up with them to see if they had anything else to say in the matter.

**Comment by JamesJB77** [comment]
@jsergio Orion dropped the topic.  Tikipeter (Fen developer) has shown interest in helping develop something for NZBs. At first, he also suggested adding it to ResolveUrl but I told him your stance on the topic.  Hopefully we can find another way.
