### ISSUE TITLE
Metahandler

### ISSUE THREAD

**Issue by lukkie112** [jsergio123/script.module.resolveurl#247]
Hi Jsergio

In the past you was a great supporter for script.module.metahandler

Now there is a problem with them since the last TVDB Updates

At no Streaming Addon it is possible to set Episodes "Marked as Watched".

Movies working well

So I please you to make a new repo branche and fix this metahandler bug

Thanks

**Comment by kasi45** [comment]
+1
many thanks

**Comment by bjgood** [comment]
Same problem. Would be nice if this was fixed. You can use Trakt to avoid this, though.

Happy holidays, JSergio, to you and yours. Relax, and have an eggnog. ;).

**Comment by bjgood** [comment]
Can't say for everyone, but on my system "Marked as Watched" started working again (this is with Trakt disabled). If someone else can confirm...that would be great.

Happy Holidays, everyone. :).

**Comment by eeden003** [comment]
I'll also check it, thanks for the info ! 😃

Op wo 25 dec. 2019 18:18 schreef bjgood <notifications@github.com>:

**Comment by bjgood** [comment]
"Marked as Watched" seems to have stopped working for me again.

Later...

**Comment by host505** [comment]
(although this has nothing to do with present repo, here goes:)
Do you guys having problems marking stuff as watched with local indicators happen to have metahandler v3.99.x?
It seems some repos import this newer version from eldorado's git, but some add-ons have to slightly adjust to be compatible with it: remove the `praparezip=False` arguments from the metahandler calls on their playcount.py, as that parameter was removed from mh 3.99.x.
This should also be compatible with older versions of mh, as `False` was the default value of that parameter anyway - not sure why most add-ons put it there.

So, either downgrade metahandler, or convince your add-on's maintainer to do the change I suggested above.

**Comment by bjgood** [comment]
> (although this has nothing to do with present repo, here goes:)
> Do you guys having problems marking stuff as watched with local indicators happen to have metahandler v3.99.x?
> It seems some repos import this newer version from eldorado's git, but some add-ons have to slightly adjust to be compatible with it: remove the `praparezip=False` arguments from the metahandler calls on their playcount.py, as that parameter was removed from mh 3.99.x.
> This should also be compatible with older versions of mh, as `False` was the default value of that parameter anyway - not sure why most add-ons put it there.
> 
> So, either downgrade metahandler, or convince your add-on's maintainer to do the change I suggested above.

Hey host505,
I'm running metahandler 3.0.2.

**Comment by jsergio123** [comment]
the metahandler is being maintained here (https://github.com/Eldorados/script.module.metahandler) by Eldorado. I won't touch it as he is still active.
