### ISSUE TITLE
in valid_url magnet - hanging system -realdebrid

### ISSUE THREAD

**Issue by morpheouso** [jsergio123/script.module.resolveurl#252]
When I have select an item which is popular and has many uploads this will hang kodi. If I turn off torrent support this doesn't occur. After a few minutes it will return to previous screen with no links being shown. I see about 40k lines like this in my debug log: 

ResolveURL: in valid_url magnet:?xt=urn:btih:2d564c0bb8fb5a58b42709d9b3a76....

RPi 3 Libreelec 9.2

**Comment by jsergio123** [comment]
@morpheouso I need to see an entire Debug log.

**Comment by morpheouso** [comment]
It's a bit long so I uploaded it [here](https://www.filehosting.org/file/details/841096/kodi.log)
