### ISSUE TITLE
mp4upload stop working

### ISSUE THREAD

**Issue by sviet2k** [jsergio123/script.module.resolveurl#254]
Hi,

I would like to let you know Kodi throws following error when trying to play mp4upload resolved link:
Peer certificate cannot be authenticated with given CA certificates

Can you please fix this issue when you have time?

Link: hxxxs://www.mp4upload.com/embed-qfteurq1jwip.html

Thanks a lot for sharing this script.

**Comment by Gujal00** [comment]
This is not a SMR issue, Kodi comes with its own cert store `C:\Program Files\Kodi\system\certs\cacert.pem` and if the issuer is not in that, then it will throw up the above error.
It can be fixed manually by adding the issuer cert to the store or wait for Kodi to update it in their next release
The issuer CA is `Sectigo RSA Domain Validation Secure Server CA`

**Comment by Gujal00** [comment]
@sviet2k you can add `verifypeer=False` header to your final resolved url and Kodi will ignore the cert

**Comment by sviet2k** [comment]
It's working. Thx a  lot for your help

**Comment by androidrepublica** [comment]
> @sviet2k you can add `verifypeer=False` header to your final resolved url and Kodi will ignore the cert

sorry, where to add this?

**Comment by Gujal00** [comment]
@androidrepublica I have done a patch in SMR to include this header in the SMR plugin itself #272 
you dont have to do anything else
