### ISSUE TITLE
File Host

### ISSUE THREAD

**Issue by Greenhousecafe** [jsergio123/script.module.resolveurl#26]
Hi J,
Would it be possible to add tocloud as a host to the resolver please?.
Here's an example https://tocloud.co/zw2u455hfyxq.
Thank you mate.

**Comment by jsergio123** [comment]
@Greenhousecafe created
https://github.com/jsergio123/script.module.resolveurl/commit/77de3a0986ad132c02aaaf22f3348c3aabf92c51

**Comment by Greenhousecafe** [comment]
Thank you 👍🏻😎
