### ISSUE TITLE
Hxload Link

### ISSUE THREAD

**Issue by androidrepublica** [jsergio123/script.module.resolveurl#268]
Hi jsergio123,

Would it be possible to add hxload as a host to the resolver please?.
Here's an example https://hxload.co/embed/3a9h7pc2njw1
Thank you mate.

**Comment by Twilight0** [comment]
This one doesn't play at all.

**Comment by androidrepublica** [comment]
> This one doesn't play at all.

it play. just need to click it few time due to ads
