### ISSUE TITLE
Please fix Vidlox resolver

### ISSUE THREAD

**Issue by antrrax** [jsergio123/script.module.resolveurl#280]
sample link:
https://vidlox.me/embed-v3qxnerrp89k

Thanks!

**Comment by Gujal00** [comment]
Doesnt seem to be a problem with the resolver. The site struggles on the browser itself and timesout frequently

**Comment by antrrax** [comment]
this sample link:
https://vidlox.me/embed-ewofphdl1trs

show this error in log file:
```
22:58:52.361 T:140098613346240  NOTICE: VideoPlayer: Opening: https://c42.vidlox.me/hls/,oudvgoco7vtk2yixv7rouajqihh5a7qxeptzfzpxuz5ubujh5wg3t2ygv5na,.urlset/master.m3u8|Referer=https%3A%2F%2Fvidlox.me%2Fembed-ewofphdl1trs.html&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A61.0%29+Gecko%2F20100101+Firefox%2F61.0
22:58:52.361 T:140098613346240 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
22:58:57.706 T:140096513468160  NOTICE: Creating InputStream
22:59:15.958 T:140096513468160  NOTICE: Creating Demuxer
22:59:21.067 T:140096513468160   ERROR: OpenDemuxStream - Error creating demuxer
22:59:21.067 T:140096513468160  NOTICE: CVideoPlayer::OnExit()
22:59:21.087 T:140098613346240  NOTICE: CVideoPlayer::CloseFile()
22:59:21.087 T:140098613346240  NOTICE: VideoPlayer: waiting for threads to exit
22:59:21.087 T:140098613346240  NOTICE: VideoPlayer: finished waiting
22:59:21.119 T:140098613346240  NOTICE: CVideoPlayer::CloseFile()
22:59:21.119 T:140098613346240  NOTICE: VideoPlayer: waiting for threads to exit
22:59:21.119 T:140098613346240  NOTICE: VideoPlayer: finished waiting
```

**Comment by antrrax** [comment]
See if it helps
Another example link, disregarding the timeout problem:
https://vidlox.me/embed-2fm0as71nopo.html

Resolver is sending this m3u8 link:

https://c23.vidlox.me/hls/,oudvhxco7vtk2yixv7rouvrbimxuk6qua6d7fth2lf5ama6x3iiowdyzz44q,.urlset/master.m3u8|Referer=https%3A%2F%2Fvidlox.me%2Fembed-2fm0as71nopo.html&User-Agent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_13_6%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+Version%2F11.1.1+Safari%2F605.1.15

however the correct link should be:
https://c23.vidlox.me/oudvhxco7vtk2yixv7rouvrbimxuk6qua6d7fth2lf5ama6x3iiowdyzz44q/v.mp4|Referer=https%3A%2F%2Fvidlox.me%2Fembed-2fm0as71nopo.html&User-Agent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_13_6%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+Version%2F11.1.1+Safari%2F605.1.15

**Comment by Gujal00** [comment]
The stream was changed to m3u8 from mp4 intentionally a while back as m3u8 had more chance of playing than the mp4 stream from their servers, Overall it is a very slow server so timeout most of the time.
