### ISSUE TITLE
not an issue @gujal00 it's request

### ISSUE THREAD

**Issue by jigoop1** [jsergio123/script.module.resolveurl#281]
hi @gujal00
can u pl look in to this addon "plugin.video.sonyliv" to use Indian IP address as using in  "plugin.video.voot" this one work in us, but not  "plugin.video.sonyliv" this one.
i try to find issue option in yr repo but i can't, so i took libert to post here, but if u thinks this is unappropriate i can delete this .
thanks in advance

**Comment by Gujal00** [comment]
If it was possible, don't you think I would have coded it that way? ;-)
It can't be done for SonyLiv

**Comment by jigoop1** [comment]
@Gujal00  
hi here is some change, i did in voot to add ip ,i thought u may like it to add in original addon [https://gist.github.com/jigoop1/a68867d0e6644fea52f96165df7c8828](url)
btw i appreciate all yr work.

**Comment by Gujal00** [comment]
@jigoop1 will adapt it when I work on a Kodi19 compatible release
