### ISSUE TITLE
New resolver issues

### ISSUE THREAD

**Issue by tetzy** [jsergio123/script.module.resolveurl#286]
For the past week or so, I've been receiving errors when attempting to open Jetload, Datoporn and Mixdrop files. Always the same error, just with a different provider named. 

Example,
 
Resolve failed
Jetload link could not be resolved

![Screenshot_2020-02-15-01-55-43](https://user-images.githubusercontent.com/59111079/74589201-785e9100-4fc0-11ea-9d75-a82c69b5b5b1.png)

![Screenshot_2020-02-15-01-31-06](https://user-images.githubusercontent.com/59111079/74589199-7268b000-4fc0-11ea-8980-65e88fdf27ae.png)

![74545847-7a353f80-4f41-11ea-9bb3-ae0d91a917d0](https://user-images.githubusercontent.com/59111079/74589326-8d87ef80-4fc1-11ea-8801-bbae947b7135.png)

Any help fixing this problem would be greatly appreciated. 
Thank You.

**Comment by Gujal00** [comment]
Mixdrop has already been fixed in git
jetload are enforcing Google ReCaptcha v3 and cant be bypassed in code for now

datoporn need to be fixed in smr.xxx. @jsergio123 please merge the PR 8 in smr.xxx git

**Comment by mbebe** [comment]
jetload has to be paired at https://jlpair.net/
after this we have m3u8 stream_link at https://jetload.net/api/fetch/ + id
:-)

**Comment by Gujal00** [comment]
@mbebe Thanks for the info. resolver fixed
