### ISSUE TITLE
New Resolver NOT an Issue

### ISSUE THREAD

**Issue by lukkie112** [jsergio123/script.module.resolveurl#289]
There are some a new resolvers like following :
Please can you add them to resolveurl

saruch.co
Excample: https://saruch.co/video/aC3eg829JfQ6ulF

streamwire.net
Excample: https://streamwire.net/8wejcihjtpr9

vidfast.co
Excample: https://vidfast.co/oz2e9l82rffu.html

**Comment by Gujal00** [comment]
streamwire is done in #305

**Comment by Gujal00** [comment]
vidfast is done in #309

**Comment by Gujal00** [comment]
saruch.co streams can be resolved but unable to be played in Kodi 18
The resolved stream plays happily on VLC, so may be it could be played using inputstream.ffmpegdirect, unfortunately it is only available for Kodi 19, so cant do much for now
