### ISSUE TITLE
Entervideo isn't working

### ISSUE THREAD

**Issue by kylesheila** [jsergio123/script.module.resolveurl#29]
Hello jsergio, Entervideo has changed something and is not resolving. Tried looking at log but not sure what the issue is

**Comment by Gujal00** [comment]
@jsergio123 it is failing as SMR is using a defunct UA. Using any other UA works.
```
curl -I http://185.176.192.20/vids/<-edited->___5a3de7817874b.mp4 -e http://entervideo.net/ -A "Mozilla/5.0 (Windows NT 6.3; Win64; IA64; Trident/7.0; rv:11.0) like Gecko"
HTTP/1.1 403 Forbidden
Server: nginx/1.10.3
Date: Mon, 20 Aug 2018 00:08:30 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive

curl -I http://185.176.192.20/vids/<-edited->___5a3de7817874b.mp4 -e http://entervideo.net/ -A iPad
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Mon, 20 Aug 2018 00:03:31 GMT
Content-Type: video/mp4
Content-Length: 633247129
Last-Modified: Sat, 23 Dec 2017 05:29:11 GMT
Connection: keep-alive
ETag: "5a3de9a7-25be9599"
Expires: Wed, 28 Nov 2018 00:03:31 GMT
Cache-Control: max-age=8640000
Access-Control-Allow-Headers: *
Access-Control-Expose-Headers: Server,range,Content-Length,Content-Range
Access-Control-Allow-Methods: GET, HEAD, OPTIONS
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
```

**Comment by jsergio123** [comment]
@Gujal00 entervideo uses the generic resolver which uses a random user agent. I have removed the IE user agent and substituted it for the EDGE user agent. Let me know if this fixes the issues. Thanks for debugging it.
https://github.com/jsergio123/script.module.resolveurl/commit/917c4eafa9799689f374a8aff1f55cb2edf18895
https://github.com/jsergio123/script.module.resolveurl/commit/dbd94195016ca9361bd38aa55f564d3a3838552e

**Comment by kylesheila** [comment]
You guys are awesome, thanks so much for all you do

**Comment by Gujal00** [comment]
@jsergio123 
I think the issue is still there as I see this in the final request
```User-Agent=Mozilla/5.0 (Windows NT 6.3; Win64; IA64; Trident/7.0; rv:11.0) like Gecko```
The issue is IA64 architecture for Windows doesn't exist, so I presume that UA is rejected
Edge UA is as below
```Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134```
I did a quick check on where it could be coming from and I see it defined here
```lib/resolveurl/lib/net.py:FEATURES = ['; WOW64', '; Win64; IA64', '; Win64; x64', '']```

**Comment by Gujal00** [comment]
@jsergio123 Yeah, I think it is better to have some 10 latest UAs from a few different platforms in common.py and be done with it

**Comment by jsergio123** [comment]
@Gujal00 here try this please https://github.com/jsergio123/script.module.resolveurl/commit/7df9e61b7058305961a4b087fd3c85917b9cb758

**Comment by Gujal00** [comment]
Yes, entervideo works now with the new common.py. Thanks

**Comment by jsergio123** [comment]
Great thanks for everything
