### ISSUE TITLE
opensv.biz

### ISSUE THREAD

**Issue by antrrax** [jsergio123/script.module.resolveurl#291]
How to resolve this url:

https://opensv.biz/drive.php?bk=ZDNJTWF4QVhBVmxsbHRBSForQ3pGT2tjL3lPTXZRUGk3QU0xMXZsbmhDaz0=

**Comment by azzy9** [comment]
Since it is just using a <source> tag, the generic resolver should work.
But that link looks like it is just a wrapper for https://www.bkseries.com, and not a host itself.

**Comment by Gujal00** [comment]
Yes just a wrapper for google video, should be handled by scraper itself and not by SMR
