### ISSUE TITLE
openload problem

### ISSUE THREAD

**Issue by ebs111** [jsergio123/script.module.resolveurl#3]
hi,
first of all great addon THANKS.
since 2 days ago there is aproblem with resolving OPENLOAD, the pair screen pops up and after pair there is an error getting the link
here is the error for example:
URLResolver: Stream UrlOpen Failed: Url: https://17wy0s2.oloadcdn.net/dl/l/a6lWNfmQOXfCHcAG/7StlLIohfJA/Black.Panther.2018.ENG.HDCAM.x264%5BSpaceMov%5D.MP4.mp4?mime=true HTTP Code: 500 Msg: Internal Server Error (ENCODED)
please help.
thanks a lot.

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.resolveurl/pull/4
