### ISSUE TITLE
support on primewire links

### ISSUE THREAD

**Issue by bugatsinho** [jsergio123/script.module.resolveurl#31]
mate is there any possibility for primewire links plugin?
they are using eval packed to encrypt the links! i know how to do the decryption but it will be used on universal scrapers and i dont want to do multiple requests for no reason!
link example
https://primewire.unblocked.vet/go.php?title=Crazy-Rich-Asians&url=88437efa5391cc71861c9ad5c9a633cd25526eb5==&id=1534347&loggedin=0
thanks mate for any questions contact me!

**Comment by azzy9** [comment]
Hi @bugatsinho,
The resolveUrl module is for resolving URL's for video hosts,
not for helping scraping & decrypting links before you get the link to the video host.
The link supplied is a link for primewire which has embedded a link to openload which is the video host.

On another note, Primewire does not seem to do a major job of hiding the link. you just need to unpack the packed script ( begins with "eval(function(p,a,c,k,e,d)"). but this is not repo to help you with this issue.

**Comment by bugatsinho** [comment]
@azzy9 so you are suggesting me to a website that provides more or less 40-100 links per title to start making requests to unpack every link?really?
seems you thing im stupid!
thank you!
as a reminder @jsergio123  did a resolver for the mehliz website...

**Comment by jsergio123** [comment]
If I remember correctly the mehliz website did indeed host some of the content themselves as well as linking to other hosts. Probably why I made an exception for them.

**Comment by bugatsinho** [comment]
@jsergio123 did you understand the reason im asking that mate?
if you dont want i will pass!i did a request/question

**Comment by azzy9** [comment]
@bugatsinho,
What I am saying is:
1. that Primewire is not a videohost
2. that for anybody to get a video link from Primewire they would have to unpack the link. If you decide to do it for every link or not is up to you. but if the resolveurl module did do it or not, the amount of requests would be the same.

**Comment by bugatsinho** [comment]
@azzy9 how the smr will do all those requests are you saying?if i remember correctly the smr resolves always the one link the user hit!so it will be 1 request to the primewire site and one to the real provider of the link!
