### ISSUE TITLE
New resolver not an issue

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#313]
There's a new resolver can you added on resolveurl please,

example link:
https://video.sibnet.ru/video3872126-Veselaya_pesnya_o_pelmenyah/

**Comment by Gujal00** [comment]
Created in https://github.com/jsergio123/script.module.resolveurl/commit/d23fdf9f82f36495293ca0d352a265bee327e40d

**Comment by soter80** [comment]
tanks guy
