### ISSUE TITLE
Sibnet.ru 

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#314]
2020-03-27 22:30:14.710 T:32258   ERROR: CCurlFile::Open failed with code 404 for 
 
Wen release the resolver it's all OK now the log return this message, but the link is online

**Comment by Gujal00** [comment]
Please do not put infringing links on the issue register, if you need to, then put them in a expiring pastebin and then put the pastebin link here.
I do not see an issue, it plays fine. Check again

**Comment by soter80** [comment]
I've checked and it's working probably it a temporary error, forgive my two mistake. Thanks again
