### ISSUE TITLE
5.0.40 on your repo ?

### ISSUE THREAD

**Issue by DjDiabolik** [jsergio123/script.module.resolveurl#316]
because you don't push this version on your personal zip repo ?

**Comment by azzy9** [comment]
jsergio no longer maintains it, gujal does.
it is still developed here but it get pushed to his repo instead.
Gujal's repo: https://github.com/Gujal00/smrzips

**Comment by DjDiabolik** [comment]
Oh it's so curios...... it's this @Gujal00 have a personal repo i can install/setup on my kodi to maintain updated this addons ? Need to see......

**Comment by Gujal00** [comment]
No, there is no personal repo for the smrzips as they are script modules and the repo if created would always show empty
It is best added as `<dir>` by other repos who depend on SMR

**Comment by DjDiabolik** [comment]
> 
> 
> No, there is no personal repo for the smrzips as they are script modules and the repo if created would always show empty
> It is best added as `<dir>` by other repos who depend on SMR

Ah.. if an addons use ResolveURL problably it's be installed this as dependency and it's no need to have an repo installed... exactly ?

**Comment by Gujal00** [comment]
Correct.
