### ISSUE TITLE
Gounlimited files broken?

### ISSUE THREAD

**Issue by tetzy** [jsergio123/script.module.resolveurl#317]
For the past week or so, gounlimited files have been returning the following error:

Resolve failed
Gounlimited link could not be resolved

I get the same error for all gounlimited files, from all providers (Freepornstreams, XXXstreams.org etc). 

Any help would be greatly appreciated, self-quarantine leaves precious little to do...

**Comment by Gujal00** [comment]
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/e16746e2e1c316fe3aeec2aa8e5f11d1c80f16fa
