### ISSUE TITLE
Newby question regarding fixes

### ISSUE THREAD

**Issue by tetzy** [jsergio123/script.module.resolveurl#319]
Sorry if questions are out of bounds here, I couldn't find a link to post directly to Gujal00.

I'm still seeing the error (Resolve failed Gounlimited link could not be resolved) despite being fixed in e16746e as reported by Gujal00. 

Question: Does that fix automatically update Ultimate Whitecream, or do I have to update it myself?

**Comment by Gujal00** [comment]
Please do not discuss about addons here, it is upto the repository of the addon to maintain dependency links. From what I can see the uwc repo points to jsergio's zips which wont be updated since 5.0.38
