### ISSUE TITLE
NETU

### ISSUE THREAD

**Issue by blackghostaddon** [jsergio123/script.module.resolveurl#322]
any  help to update  netu server
hxxps://netu.tv/watch_video.php?v=vH9I5z8HsGE6
and powvideo.

**Comment by L2501** [comment]
duplicate of https://github.com/jsergio123/script.module.resolveurl/issues/320
it also uses recaptcha so you will need to use a browser anyway.

**Comment by Gujal00** [comment]
netu, hqq and waaw are all the same site and they all are enforcing Google Recaptcha
No solution for now
