### ISSUE TITLE
Request OpenPlayer

### ISSUE THREAD

**Issue by xventil** [jsergio123/script.module.resolveurl#326]
Hello again!

Is it possible to add another provider/plugin? 

openplayer,

here is an example link
https://openplayer.net/player/?key=cFgvWll6M3FlUHZaK1pVN3JIQ3NiYU9CSkdoeHVham5QWTBZUHlock8xST06RFlFbGppdk9yZXo4cW43RllIYlpTNlFOelMycm83SDhNUndrb1J3bDh0VT06cCsrS3FpYUlqNnVjWEo2akE4MWxmUT09OjNpUFJ4OGhJdnd4RnorWjI4UnVWc2JScndLV3NEaGR0Z25EVld3dGJpenRCL0RtMmFSTGYvSEZOcjZjZzJYRmRwRFIzY2xmTFh4aEZZU2tLL1Y5eCtrSjMweXNWTjQ1VFhHRGZQeW5HZ2MwanJjdWFTM21raFp3VDczd2h0M3dlQ0JhdEtRcEhhZDVkc0FTTi9mTGlzTm41U2dsTzZjQXNOTDdseUtRQmFVYVk4bkZuNUorcmp6bjlkRXRlY3YwMVZvRmlLZStCT1htNmpwdmwzN0Q4MEo0VU5JZ3dxSkMrMTUrdVNORzJVTlk9

**Comment by Gujal00** [comment]
That is not a hoster, but an embedder of other hoster urls. Not a target for ResolveURL

**Comment by xventil** [comment]
ok, thanks for the answer.
