### ISSUE TITLE
streamz not working

### ISSUE THREAD

**Issue by alee6a6a** [jsergio123/script.module.resolveurl#327]
Please streamz links not working! play only 1min. intro video....thanks for your time.

**Comment by Gujal00** [comment]
seems to be working fine for quite a few links that I tested. Check if your link works on the webbrowser and if it does provide it so that it can be checked

**Comment by alee6a6a** [comment]
thx. Gujal00. if u tested then its ok.

**Comment by alee6a6a** [comment]
thx. Gujal00. if u tested then its ok.
