### ISSUE TITLE
TheVideo.me -> Vev.io

### ISSUE THREAD

**Issue by doko-desuka** [jsergio123/script.module.resolveurl#33]
They changed brand, but still have a pairing mechanism: https://vev.io/pair

Some providers are hosting episodes with it.
Example: https://thevideo.me/om7x9sv4jiaa
That link gets redirected to this: https://vev.io/j93w5kde563d

Python code to get the redirection (w/ script.module.requests):
```
import requests

# Hm, turns out the headers aren't needed. Default Session headers work fine.

s = requests.Session()
r = s.get('https://thevideo.me/om7x9sv4jiaa', allow_redirects = False)
redirectedURL = r.headers['Location'] # Points to vev.io/blablabla
```

I sent vev.io a message just now asking for the pairing API, but last time I did that with TheVideo they didn't respond. Not one bit.
Why couldn't they just put the API in public anyway...

**Comment by doko-desuka** [comment]
Vev.io still hasn't responded to my two requests for API docs, one from a week ago and another from two days ago.  
Did you have any luck?

**Comment by jsergio123** [comment]
sorry didnt get a chance to look yet

**Comment by doko-desuka** [comment]
(Closing this since theres a PR for it.)

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.resolveurl/commit/49e04a55248739d20bd3dcd70c00f822a5b969a5
