### ISSUE TITLE
wstream not resolve

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#330]
https://pastebin.com/raw/iZ8mfQ29

here is the log for this link
hxxps://wstream.video/1yvfcxozfqz1

**Comment by Gujal00** [comment]
May be dependent on location, resolves correctly in my location
does the link play in browser?

**Comment by soter80** [comment]
Tkx guy for the answer, the problem depend on an upload in antiadblock plugin, because after 2 hours it works again.

**Comment by Gujal00** [comment]
not an SMR issue

**Comment by soter80** [comment]
Sorry for my mistake next time I'll wait before open an issue.
