### ISSUE TITLE
Uptobox Pin

### ISSUE THREAD

**Issue by bluedog73** [jsergio123/script.module.resolveurl#331]
Some links still requiring a pin using real debrid while others don't? Is this an issue that is always going to be around or can it be fixed?

**Comment by Gujal00** [comment]
Realdebrid, does not support uptobox, so yes SMR will fallback to its free resolver, which requires pin
If you want uptobox use a debrid provider such as Alldebrid, who support it and then SMR will play using the debrid provider and not prompt for a pin

You can check which hosters are supported by real debrid and which of those are down at this url
`https://real-debrid.com/compare`
