### ISSUE TITLE
new resolvers

### ISSUE THREAD

**Issue by alee6a6a** [jsergio123/script.module.resolveurl#332]
Hi, can u add 2x nieuwe domain resolver. Thx voor u time..
1- [videomega.co']
2- ['youdbox.com'] (copy of ClipWatching works.)

Adult link !!! view-source:hxxps://xxxstream.me/student-bodies-8/

**Comment by Gujal00** [comment]
Added in 5.0.44 release

**Comment by alee6a6a** [comment]
perfect. thx.

Op di 28 apr. 2020 om 00:07 schreef gujal <notifications@github.com>:
