### ISSUE TITLE
Skip popups doesn't work as expected

### ISSUE THREAD

**Issue by jkfdskfmsl** [jsergio123/script.module.resolveurl#333]
So, skip popups DOES indeed make the popup for those annoying 'pair' sites not show up, but then the resolver tries to load something anyways and I can't figure out what it's doing. I've tried all sorts of code mangling myself to just get it to fail back to the next host in the list, but no matter what it just seems to ghost load whenever encountering a host with a pair link. This results in the progress dialog of sources being cleared, and me having to guess where I was in the search dialog to find where it failed so I can start at the next possibly-viable host. Why don't hosters with popups just fail silently and move on to the next host when that option is enabled? I tried to fix it myself, but I sure couldn't find where in the code to set that up. Opening this issue because I assume you know the code better than me.  All I can say is that it's surely possible, URLs that don't work at all do pass on to the next host down the list. I just can't quite figure out where that happens, and how I'd get the offending pair hosters to not even attempt to resolve but instead just go there instead. I can't think of why anyone would want to attempt to resolve hosters that haven't been paired, but if you can think of a reason maybe make it a second option for 'Attempt to resolve anyways'. Otherwise, all pair-requiring hosters should just pass the buck to the next host on the list if the popup/wait for pairing option is disabled.

**Comment by Gujal00** [comment]
What you are describing has nothing to do with ResolveURL but with scraper addons. I can't comment about those addons, but if they are operating correctly, they will be passing the link to ResolveURL to see if it is supported before populating the list that gets displayed. If popups are disabled in SMR settings, any site that requires pairing would show as unsupported when the addon checks with SMR, means should not even be listed. So if you are having issues with scraper addons, take it up with the addon developer. There is nothing to be done in SMR

**Comment by jkfdskfmsl** [comment]
That would sure explain why I couldn't find where the problem was in SMR lol. Could you please provide me with the name of a scraper addon that does operate correctly? It'd sure be easier to just use one that works than doing all that code digging with the ones I have that I guess are ignoring the not-supported flag for some reason.
