### ISSUE TITLE
sibnet not work

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#334]
hi guy sibnet don't work i've attached log
[log.txt](https://github.com/jsergio123/script.module.resolveurl/files/4559714/log.txt)

**Comment by Gujal00** [comment]
Partial logs are of no use unfortunately.
Need full **debug** log, Thanks

The test embed links that I do have from sibnet work correctly, so most probably something on your end

**Comment by soter80** [comment]
I've posted entire log here
https://pastebin.com/raw/hk9QBz8B

**Comment by Gujal00** [comment]
From the log I can see that it resolved the url correctly and passed it to Kodi player for playback. It is not an issue with SMR
More information would have been there if you had provide the debug log as I requested. The log that you have provided is not a debug log and is not very helpful

**Comment by soter80** [comment]
Sorry guy this is kodi log, where I find debug log?

**Comment by Gujal00** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by soter80** [comment]
So guy now all Is work correctly, sibnet have a downgrade of streaming now resolved
