### ISSUE TITLE
Alldebrid v4 api update

### ISSUE THREAD

**Issue by kingnev69** [jsergio123/script.module.resolveurl#337]
Hi since beginning of may alldebrid has had an update that stops alldebrid working with kodi, is there any chance this new code will be added in an update?

**Comment by Gujal00** [comment]
This has been answered many times before.
This is nothing to do with Kodi itself.
Alldebrid api v4 changes were implemented in resolveurl over a month ago and has been working fine even before May 1.
Any addon that uses resolveurl didnt stop working on May 1. If the addon stopped then that addon is not using resolveurl, so talk to the addon developer

**Comment by xyzfre** [comment]
Weird thing is I’ve been having the same issues ever since the last update of ResolveUrl 5.0.46,prior to this last update it was working fine 5.0.45

**Comment by Gujal00** [comment]
So unless you provide a full debug log, I wont be able to deduce the issue.
I have tested Alldebrid resolver again for supported hosters and it works perfectly fine as expected.

Update: There is an issue with magnets/torrents handling in Alldebrid and seems to be at Alldebrid server end. Waiting for a response from them

**Comment by Gujal00** [comment]
Alldebrid have fixed their end and now magnets cached and uncached are working fine

**Comment by kingnev69** [comment]
Hi thanks for your reply, so I use venom, the crew, tempest and seren, yet no alldebrid links work, I have tried closing kodi and my vpn down opening kodi to link my alldebrid account, uninstalling addons and re-installing, so am confused as to why it won’t work? I know it’s nothing to do with resolve but your the only person that has got back to me after posting everywhere else, do you have any other ideas on how to get this working please?

**Comment by Gujal00** [comment]
Venom certainly uses ResolveURL and should work with alldebrid, can you reset alldebrid authorisation in ResolveURL and reauthorise and test.
Seren has its own code for Alldebrid and does not use ResolveURL. I dont know about the others.

**Comment by kingnev69** [comment]
Mate you’re an absolute legend, working fine now, thank you so much 👍

**Comment by xyzfre** [comment]
> Alldebrid have fixed their end and now magnets cached and uncached are working fine

So it was something on their end this was driving me nuts for the past two days definitely going to check when I get home to see if mines is working as well really appreciate your response and for your amazing work
