### ISSUE TITLE
mixdrop / jetload

### ISSUE THREAD

**Issue by madnesofjuice** [jsergio123/script.module.resolveurl#338]
Mixdrop and jetload not working. I tried the links on browser and it works there.
Any fix for that?

**Comment by Gujal00** [comment]
seems to be working fine. give sample non working embeds for troubleshooting

**Comment by madnesofjuice** [comment]
Now its working mixdrop, but when im trying to play jetload it appears a window to pair to jlpair.net but i cant accest that site(502 bad gateway)

**Comment by Gujal00** [comment]
Yep, it is a known issue with the jlpair.net site, it is frequently down and nothing can be done about it
