### ISSUE TITLE
Request for a resolver

### ISSUE THREAD

**Issue by AkosiKepweng** [jsergio123/script.module.resolveurl#34]
Hi jsergio,
want to request for a resolver if possible, i think this is a googlevideo
https://www.blogger.com/video.g?token=AD6v5dyX0r9VSsaRq1kCxrIQ45FFE6QiYq8bGimoz-hv_AekQma80nOCyrpa6gEYg5tZ6pCgUFDK33PuibZJrhXBgjPA41MudzwyX9EJ7PGXnbKF4yxcq_z3KN4_0Hxexw8EPvUDE6Ec
thanks

**Comment by jsergio123** [comment]
can you send me some more examples?

**Comment by AkosiKepweng** [comment]
thanks jsergio,
https://www.blogger.com/video.g?token=AD6v5dxXUlyOuv4ffWDDCptsFuq9tBCUGf8_G1nbuKRHILyhBdGx8G1bgDsy4aZyKx_YozRN2zAWQ8dW8uuqk3yeyUEMq8wiz_aoVyZcd-O3ewsJhWrvQVrNj2CJvQP3CCc-BRnxnN0

https://www.blogger.com/video.g?token=AD6v5dw1g9Q0SaFPuSzji-gqJSZqmwzwRx-AMcD7hDDuFw8Vvz8Lv89W7smLzMeg1AxMlEeJOVJS7DPUfZxroNLehi5qSu1uKOK7e43pj74zjSiIXD8Rh65O2hWdIu0IMOMz-vlbZYHI

https://www.blogger.com/video.g?token=AD6v5dyxNDpfpqaDXf-5iOamuFDEZhPpeSJp2tCjU0yVC7qP1nPUW6OLlI9kFcDzJwgtk80X4_Y8TlRjF5lrlFvLjXHtdCkyU1ZFm4zwoztFPmhf689cmrO5iRvsgFEn5P08aLEjBGCv

**Comment by jsergio123** [comment]
added support to the googlevideo plugin but this is just a quick hack till I decide what I want to do with this plugin
https://github.com/jsergio123/script.module.resolveurl/commit/9e917d0af286341eb32e28397e1dec9af41aad72
