### ISSUE TITLE
recaptcha

### ISSUE THREAD

**Issue by ghost** [jsergio123/script.module.resolveurl#340]
i found a solution recaptcha
where works
hope you can incorporate that
please check
https://github.com/kodiondemand/addon
host wstream
tnx

**Comment by Gujal00** [comment]
Is there an issue with this plugin? I dont see any issue playing embeds from that site.
If it is not working for you, provide an example embed

**Comment by ghost** [comment]
I will send you 3 examples on the links
```
https://wstream.video/video.php?file_code=wel20rj0rjt0
https://wstream.video/video.php?file_code=miikdobhlh3d
https://wstream.video/video.php?file_code=o5an2ffitlho
```
used recaptcha please see this addon
there they can be solved directly kodi
hopefully that would be for netu & co
also possible

**Comment by Gujal00** [comment]
The above are using a new embed pattern, added to the existing resolver in https://github.com/jsergio123/script.module.resolveurl/commit/2770e68480e8b44fea95d9a59853e284b59fe539
netu & co is google invisible recaptcha, can't be done
