### ISSUE TITLE
anavids not work

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#341]
Hi guy anvids.com not resolve link
hxxps://anavids.com/ghopifdq5umx.html
here is the debug log>> https://pastebin.com/raw/yqmmwcPe

**Comment by Gujal00** [comment]
Certificate issue
`Failed: Peer certificate cannot be authenticated with given CA certificates(60)`

**Comment by soter80** [comment]
Link works good on browser... I've reed this in debug log but I don't understand it

**Comment by Gujal00** [comment]
Kodi has its own cert store and does not use the browser certstore, so probably the ca signing cert that site is using is not there on the kodi cert store

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Gujal00** [comment]
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/ca3154bc596d3b8743980322bc7c523ea4907f7f

**Comment by soter80** [comment]
thanks guy
