### ISSUE TITLE
Use resolveurl without kodi

### ISSUE THREAD

**Issue by sraedler** [jsergio123/script.module.resolveurl#343]
How is it possible to use resolveurl without kodi?

I already installed kodistubs but unfortunately it is not working.
Could you please propose a possible usage?

Is it maybe possible to ignore import errors and call the resolve function?

**Comment by Gujal00** [comment]
ResolveURL project is solely for resolving urls within kodi.

If you are looking for a standalone resolver have a look at the [streamlink project](https://streamlink.github.io/)

**Comment by sraedler** [comment]
Thanks!
The problem is that streamlink do not support sites like nxload...

Do you know other libraries?

Otherwise I may need to remove Kodi stuff from resolveurl
