### ISSUE TITLE
Playlist Player: skipping unplayable item: 0

### ISSUE THREAD

**Issue by trekker77** [jsergio123/script.module.resolveurl#344]
Since ver 5.1, no hosts shown when trying to scrape for TV Series streams using AliveGr addon. 'Playlist Player: skipping unplayable item: 0'.  Log: https://bit.ly/2BeR06B

**Comment by Gujal00** [comment]
log not accessible

**Comment by trekker77** [comment]
https://ares-project.uk/logupload/log.php?id=271383

**Comment by Gujal00** [comment]
Need a debug log, the log provided has no debug information
Enable debug from the system menu before using the addon

**Comment by trekker77** [comment]
https://ares-project.uk/logupload/log.php?id=271384

Thanks.

**Comment by Gujal00** [comment]
Sorry, I don't see any errors relating to ResolveURL in the logs, you may have to contact the addon author to further debug.

**Comment by trekker77** [comment]
Ok. Thank you for your time.
