### ISSUE TITLE
Wstream not resolve 

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#347]
After last update wstream not work 

[Debug log ](https://www.dropbox.com/s/ab59pqrzgjahjt0/kodi.log?dl=1)
Ex link: hxxps://wstream.video/w9vy0isq9haf 
This link is working in browser

**Comment by Gujal00** [comment]
It's got nothing to do with the last update. wstream have modified their page code which they do regularly and is normal for it to break in SMR
New match pattern added in https://github.com/jsergio123/script.module.resolveurl/commit/effabe89ad255535180b05ce8659c93b091e79bd

**Comment by soter80** [comment]
I know it's not connected to the latest SMR update, but I changed line 30 of the code generic_pattern=True) and it works correctly, I've proposed change.
