### ISSUE TITLE
Mixdrop not working

### ISSUE THREAD

**Issue by neires** [jsergio123/script.module.resolveurl#351]
Mixdrop not working. 
I tried the links on browser and it works there.
hxxps://mixdrop.co/f/9n1dzxo6bzz97g
Any fix for that?

**Comment by Gujal00** [comment]
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/dd1a08956913f0ebb539a5a050902df3f2831630

**Comment by neires** [comment]
> 
> 
> Fixed in [dd1a089](https://github.com/jsergio123/script.module.resolveurl/commit/dd1a08956913f0ebb539a5a050902df3f2831630)

THX for fix, working now :)
