### ISSUE TITLE
.strm files

### ISSUE THREAD

**Issue by dvdbouns** [jsergio123/script.module.resolveurl#358]
Hello,

it's possible to call your script with a .strm files ?

Thank you

**Comment by Twilight0** [comment]
Not directly, you have to call a video addon first which uses resolveurl.

**Comment by dvdbouns** [comment]
Thank you for your return,

do you know of an easy to use video plugin?

**Comment by dvdbouns** [comment]
Thank for plugin.video.resolveurl-tester 👍

**Comment by Gujal00** [comment]
You can use SMR Link Tester from SMRzips repo
in STRM, add the link as follows, you need to urlencode the actual embed link
`plugin://plugin.video.smr_link_tester/?link=https%3A%2F%2Fvoe.sx%2Fh4ev93ohcahk&mode=play_link`
