### ISSUE TITLE
OK.Ru resolves to CDS but fails to play

### ISSUE THREAD

**Issue by Philps** [jsergio123/script.module.resolveurl#36]
https://ok.ru/video/<removed>

Resolves to:

http://vd51.mycdn.me/?expires=1536561222314&<removed>

ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
08:34:04.575 T:1868   ERROR: CCurlFile::Open failed with code 0 for http://vd51.mycdn.me/<remvoed>

**Comment by jsergio123** [comment]
I will check it out. It might just be network issue related to the cdn causing the timeout. Also be careful posting urls that include ip addresses. You might want to edit your post to remove any ip addresses.

**Comment by jsergio123** [comment]
@Philps can you please link me to the video you are trying to resolve as this plugin is playing fine for me.
