### ISSUE TITLE
How to install this script

### ISSUE THREAD

**Issue by nulleduser0** [jsergio123/script.module.resolveurl#364]
Anyone can help me with installing this script on Web server

**Comment by Twilight0** [comment]
The purpose of this script is to be run within Kodi and its forks. You can't use it on a server cause it calls kodi's python modules. Unless you adapt it to suit your needs, it simply won't work. Use youtube-dl instead. or even something like this: https://github.com/Rudloff/alltube

**Comment by nulleduser0** [comment]
Thanks dude
