### ISSUE TITLE
NXLOAD now requires to click "allow" button before video start

### ISSUE THREAD

**Issue by Philps** [jsergio123/script.module.resolveurl#37]
Example: https://nxload.com/embed-i9zxnmzfgner.html

**Comment by doko-desuka** [comment]
If you search for ".mp4" in the source to that page there's a video URL. Is that what it should be playing?
[view-source:https://nxload.com/embed-i9zxnmzfgner.html](view-source:https://nxload.com/embed-i9zxnmzfgner.html)

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.resolveurl/commit/40952ffd78a3b203db40c8e86ea311bd036589b2
