### ISSUE TITLE
Latest ver from this repo

### ISSUE THREAD

**Issue by nki2bpz** [jsergio123/script.module.resolveurl#372]
Thnx for all you do. Trying to obtain latest ver from only trusted source. Ver from this repo reports as 5.0.38 while other less trusted sources show 5.1.8
![20200913_033212](https://user-images.githubusercontent.com/15946723/93012941-3f949380-f572-11ea-9d75-87b88bfc4849.jpg)
If I update from this repo then the system continues to report update available. I apologize if this is the wrong place to report this.

**Comment by Gujal00** [comment]
As Jsergio mentioned back in March, he is not pushing new versions from his repo, so his repo stands at 5.0.38
All releases after that version are from the [ResolveUrl repo](https://raw.githubusercontent.com/Gujal00/smrzips/master/zips/repository.resolveurl/repository.resolveurl-1.0.0.zip)
So if you want to be sure of getting official releases install that repository.
