### ISSUE TITLE
New Resolver

### ISSUE THREAD

**Issue by poortuga** [jsergio123/script.module.resolveurl#38]
Hi Jsergio
I'm here again to ask for new resolver.. 
https://movienightplayer.com/tt5164214
Changing the imdb ID we get a lot sources from them.. 
If possible I would appreciate.. 
Thanks

**Comment by jsergio123** [comment]
this site is not a host

> NO content is managed by movienightplayer.com, NO content is uploaded by movienightplayer.com, ALL content is uploaded and hosted by 3rd party sources.
Please contact the 3rd party if you have any discrepancies!

>
