### ISSUE TITLE
abcvideo

### ISSUE THREAD

**Issue by bhai840** [jsergio123/script.module.resolveurl#380]
Hi 

I thought of contributing to the resolveurl, so I created a new plugin abcvideo.py in the plugin folder and updated the settings.xml locally, removed the md5 checksum, zipped it and imported it to Kodi (18.1). But I get a error in kodi.log. url is getting resolved but isn't picking it up.

help on this is much appreciated.

Error:
2020-10-07 10:37:15.062 T:9188  NOTICE: ResolveURL: Initializing ResolveURL version: 6.4.98
2020-10-07 10:37:17.314 T:9188   ERROR: ResolveURL: ResolverError Error - From: abcvideo Link: https://abcvideo.cc/famy2k9oahmp.html: Video not found
2020-10-07 10:37:17.324 T:8724  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.movierulz/?action=play&video=https://abcvideo.cc/famy2k9oahmp.html
2020-10-07 10:37:18.849 T:6268  NOTICE: Creating InputStream
2020-10-07 10:37:22.494 T:6268  NOTICE: Creating Demuxer
2020-10-07 10:37:22.859 T:6268   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, https://abcvideo.cc/famy2k9oahmp.html
2020-10-07 10:37:22.860 T:6268   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
2020-10-07 10:37:22.860 T:6268  NOTICE: CVideoPlayer::OnExit()
2020-10-07 10:37:22.895 T:8724  NOTICE: CVideoPlayer::CloseFile()
2020-10-07 10:37:22.895 T:8724  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-07 10:37:22.895 T:8724  NOTICE: VideoPlayer: finished waiting

Code:
import re
from lib import helpers
from lib import jsunpack
from resolveurl import common
from resolveurl.resolver import ResolveUrl, ResolverError

class AbcVideoResolver(ResolveUrl):
    name = "abcvideo"
    domains = ["abcvideo.cc"]
    pattern = '(?://|\.)(abcvideo\.cc)/(?:embed-)?([0-9a-zA-Z]+)'

    def __init__(self):
        self.net = common.Net()

    def get_media_url(self, host, media_id):
        web_url = self.get_url(host, media_id)
        headers = {'User-Agent': common.RAND_UA,
                   'Referer': web_url}
        html = self.net.http_GET(web_url, headers=headers).content

        r = re.search("script'>(eval.*?)</script", html, re.DOTALL)
        
        if r:
            html = jsunpack.unpack(r.group(1))
            src = re.search('src\("([^"]+)',html)
            if src:
                return src.group(1) + helpers.append_headers(headers) + "&verifypeer=false"

        raise ResolverError('Video cannot be located.')
 
    def get_url(self, host, media_id):
        return self._default_get_url(host, media_id, template='https://{host}/embed-{media_id}.html')

Inspect information from url:
Request URL: https://abcvideo.cc/famy2k9oahmp.html
Request Method: GET
Status Code: 200 
Remote Address: 172.64.128.34:443
Referrer Policy: no-referrer-when-downgrade
cf-cache-status: DYNAMIC
cf-ray: 5de75bccfa450e0a-MXP
cf-request-id: 05a477b41900000e0a73a0e200000001
content-encoding: gzip
content-type: text/html; charset=UTF-8
date: Wed, 07 Oct 2020 11:42:24 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Tue, 06 Oct 2020 11:42:24 GMT
nel: {"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?lkg-colo=39&lkg-time=1602070945"}],"group":"cf-nel","max_age":604800}
server: cloudflare
status: 200
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
:authority: abcvideo.cc
:method: GET
:path: /famy2k9oahmp.html
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: max-age=0
cookie: __cfduid=d71cc29db75b42dc046ab8e50fabd37fc1601973943; lang=1; aff=397; OM1ABCVIDEO_ADBLOCKPOP2max=1%7C1601973955946; file_id=653428; game=checker; ref_url=https%3A%2F%2F4movierulz.be%2Fnishabdham-2020-hdrip-telugu-full-movie-watch-online-free%2F
referer: https://4movierulz.be/nishabdham-2020-hdrip-telugu-full-movie-watch-online-free/
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: cross-site
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Edg/85.0.564.68

**Comment by Gujal00** [comment]
abcvideo plugin was removed from ResolveURL when they put their links behind Google Invisible recaptcha a few months ago. It cannot be done, same as netu/hqq/waaw
