### ISSUE TITLE
drive.google.com links not resolved

### ISSUE THREAD

**Issue by dracosc22679** [jsergio123/script.module.resolveurl#389]
During last weeks, i am unable to resolve videos from these links.
Can you please check?

**Comment by Gujal00** [comment]
same as #357 and #377 Why opening new issue when already 2 threads exist?

**Comment by Gujal00** [comment]
@dracosc22679 
I think https://github.com/jsergio123/script.module.resolveurl/commit/31a6c9043b53940c69b3643fbd79c6d20a410c55 will fix this issue, can you try and report please
