### ISSUE TITLE
SMR link tester / beeg.com not supported

### ISSUE THREAD

**Issue by semye64** [jsergio123/script.module.resolveurl#390]
Hi all,
Use SMR link tester / beeg.com not supported

https://beeg.com/1909972901 this and others fails
 
Same link out of Kodi with any browser works fine
Can you please check? Many thanks

**Comment by Gujal00** [comment]
beeg.com was never supported, and even then wont be in SMR as it is a adult site.
may be some one can write a plugin do a PR for SMR.xxx
