### ISSUE TITLE
evoload.io

### ISSUE THREAD

**Issue by kasi45** [jsergio123/script.module.resolveurl#392]
Hi,

Is there a way to resolve the links from evoload.io?

Thanks!!

**Comment by Gujal00** [comment]
Uses Google invisible recaptcha. unfortunately can't be done.

**Comment by addon-lab** [comment]
hi,
I have solved the invisible recaptcha. I am not a python programmer, but i can prepare a little python script that solve it. If you are interested I can share it with you so you can adapt it and include in resolverurl.

Let me know
Best regards
Carlos

**Comment by rabinovic** [comment]
> hi,
> I have solved the invisible recaptcha. I am not a python programmer, but i can prepare a little python script that solve it. If you are interested I can share it with you so you can adapt it and include in resolverurl.
> 
> Let me know
> Best regards
> Carlos

Hi Carlos,
i would like to have your solution to include in my project where i can't bypass Google recatcha. Thanks
Rabinovic

**Comment by Gujal00** [comment]
> 
> 
> hi,
> I have solved the invisible recaptcha. I am not a python programmer, but i can prepare a little python script that solve it. If you are interested I can share it with you so you can adapt it and include in resolverurl.
> 
> Let me know
> Best regards
> Carlos

Yes, please share the script , I will attempt to adapt it. evoload and netu/hqq/waaw resolver can be implemented then

**Comment by addon-lab** [comment]
hi,
I am going to prepare to share the recaptcha script and evoload.io script that make use of it
I am going to include scripts  for gamovideo.com and videos.sh to include too in resolverurl.

Carlos

**Comment by addon-lab** [comment]
hi,

Here it is:
https://github.com/addon-lab/addon-lab_resolver_Project

I would appreciate if you would inform me when you have updated resolveurl with the adaptation of these scripts. Also tell me which servers you have been able to solve with the reCaptcha script.

If you have any problem or need some clarification, do not hesitate to contact me.

Cheers

**Comment by Gujal00** [comment]
@addon-lab 
Thanks for the script, I have adapted it for SMR and have added evoload.io and abcvideo.cc
have a look at https://github.com/jsergio123/script.module.resolveurl/commit/c98737f64a19629d7095bc276a79bcdceab60598 and https://github.com/jsergio123/script.module.resolveurl/commit/4b1cc821413b20ef8af9fa7f3fba1f1031613de5

**Comment by kasi45** [comment]
Great job, thanks to all who participated in the solution
