### ISSUE TITLE
ANY way getting this to play using resolver

### ISSUE THREAD

**Issue by TheGridRepo** [jsergio123/script.module.resolveurl#396]
https://www.fite.tv/watch/roh-wrestling-episode-476/2p8c3/

**Comment by Gujal00** [comment]
SMR can resolve and get the m3u8 stream link
However the streams are using
`#EXT-X-KEY:METHOD=AES-128,URI="hls.key"`
I dont think they can be played directly by Kodi Videoplayer and you may have to use Streamlink to play these.
