### ISSUE TITLE
Alldebrid error 

### ISSUE THREAD

**Issue by jamos316** [jsergio123/script.module.resolveurl#397]
Hi
When I go into settings-universal resolvers-authorize my account with alldebrid it crashes and shows resolveurl error. Is there a issue with alldebrid? 
Thanks

**Comment by Gujal00** [comment]
Please post a full debug log without which it can't be diagnosed

**Comment by jamos316** [comment]
[kodi.log](https://github.com/jsergio123/script.module.resolveurl/files/5506024/kodi.log)

Is this it?

**Comment by Gujal00** [comment]
Yes it is the log, but you need to enable debug logging in Kodi Settings -> System -> Logging and then try to authorize. This will give more information on the log for diagnosing

**Comment by jamos316** [comment]
[kodi.log](https://github.com/jsergio123/script.module.resolveurl/files/5507225/kodi.log)

**Comment by Gujal00** [comment]
You are using ancient version of resolveurl
`script.module.resolveurl v5.0.38 installed`
It will not work with Alldebrid. Upgrade to the latest version which is 5.1.13 and it will work

**Comment by jamos316** [comment]
I can't see any update avaliable when in kodi, where can I download the zip or repo for the latest version?

**Comment by Gujal00** [comment]
All the addons that use resolveurl include the repo as a directory. If you are not seeing update then most probably the addons you have do not use resolveurl.
Anyway the repo zip for resolveurl is
`https://raw.githubusercontent.com/Gujal00/smrzips/master/zips/repository.resolveurl/repository.resolveurl-1.0.0.zip`

**Comment by jamos316** [comment]
Yes the update worked. Thanks for the support!
