### ISSUE TITLE
HostedMediaFile not working as expected in Kodi 19 / Python 3

### ISSUE THREAD

**Issue by jdoedev123** [jsergio123/script.module.resolveurl#402]
We use "if resolveurl.HostedMediaFile(link):"  to test for valid resolvable links. 
It works in Kodi 18 /  Python 2 but it is passing everything through including essentially non URL gibberish when running in Kodi 19 /Python 3.  Additionally, some of the links it passes through are not resolvable but Ad links etc. 
In other words the conditional is always True.

**Comment by Gujal00** [comment]
Please use
```python
if resolveurl.HostedMediaFile(link).valid_url():
```
this will work on both PY2 and PY3

**Comment by jdoedev123** [comment]
Thanks. Downloaded and installed latest SMR code. It works in PY3 / Kodi 19. I will begin regression testing in PY2 / Kodi 18 soon.

**Comment by jdoedev123** [comment]
Update, quick spot regression test in Kodi 18/ PY2 worked. Thanks again.
