### ISSUE TITLE
streamtape not working

### ISSUE THREAD

**Issue by mullafabz** [jsergio123/script.module.resolveurl#409]
Hello, Thanks for all the work with resolveurl.
Trying to play streamtape.com links but getting playback error in k0dI.
Kindly check on this.

**Comment by Gujal00** [comment]
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/a44de70b033acb94b66903f5d7687fd18713af51

**Comment by flapbird1** [comment]
Using latest 5.1.18 and keeps failing on me?
Can anyone recheck? Please
