### ISSUE TITLE
Resolver request

### ISSUE THREAD

**Issue by Sanjjay** [jsergio123/script.module.resolveurl#410]
Hi Gujal

Please can you make a resolver for mega.nz with the link below as they allow video streaming in embeded links now and not like before when it was restricted.

[https://mega.nz/embed#!PORRDAiL!yO6rchwdUxpn86CCw44YoB7U7x4hmebkRW53-4pYO9I](url)

**Comment by Gujal00** [comment]
mega.nz is a premium file hoster and not a generic streamer. The embed player that they use is a custom player which downloads individual segments of the file and decrypts in memory and display it. It is not possible to do this in Kodi as it expects a proper streaming protocol such as HLS, or DASH which mega.nz does not employ.
mega.nz is supported through the universal resolvers in ResolveURL, so if you have a debrid account it will work through that.
