### ISSUE TITLE
tvlogy not able to resolve

### ISSUE THREAD

**Issue by YoColdRain** [jsergio123/script.module.resolveurl#423]
Hello Sergio/Gujal, 

I'm having issue with tvlogy resolver to work, can someone look into this one?
@Gujal00

**Comment by Gujal00** [comment]
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/713b180c6b7d2ab6e5af89474b84bfb788abd72a

**Comment by YoColdRain** [comment]
@Gujal00  above definitely helped, but can you see how to resolve this tvlogy?
http://tellygossips.net/media.php?id=1401579

**Comment by Gujal00** [comment]
Can you check with [this commit](https://github.com/jsergio123/script.module.resolveurl/commit/a9d6f1a6c6bfc817237af29e9450e8d9e14e2031) and report back

**Comment by YoColdRain** [comment]
@Gujal00 wow, that did fix it!

I found my issue before you pasted when I saw python idle returned correct expected response but our favorite media player didn't show correct response.  And before I get to fix my own issue, your above solution fixes what I needed.

Thank you so much!
