### ISSUE TITLE
pls add streamoupload.com and yandexcdn.com resolvers

### ISSUE THREAD

**Issue by alee6a6a** [jsergio123/script.module.resolveurl#435]
Hi,
pls add streamoupload.com and yandexcdn.com resolvers.
streamoupload is same like speedostream.

_Edit: Adult links removed_

thanks

**Comment by Gujal00** [comment]
Streamoupload added in https://github.com/jsergio123/script.module.resolveurl/commit/31f8cc3599261f159ec2f833a2b4f0eda056f418 
yandexcdn cant be done due to the use of captcha, it is another alias of waaw/hqq/netu/ricchioon
