### ISSUE TITLE
Wstream error

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#440]
Wstream not resolve http error 403.

ERROR: ResolveURL: HTTPError Error - From: wstream Link: hxxps://wstream.video/1yvfcxozfqz1: HTTP Error 403: Forbidden
2021-04-03 18:01:13.462 T:22556   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):

**Comment by Gujal00** [comment]
Site behind Cloudflare DDOS Protection, cant be fixed

**Comment by soter80** [comment]
But wstream is under cloud flare ddos by many time and it not worked just to days ago.

**Comment by Gujal00** [comment]
ResolveURL does not do Cloudflare DDOS bypass for any site. It just doesnt have the capability to do that

**Comment by Gujal00** [comment]
wstream not using cflare ddos protection now, so resolver is working now
