### ISSUE TITLE
Wierd, super annoying problem...

### ISSUE THREAD

**Issue by tetzy** [jsergio123/script.module.resolveurl#442]

**Comment by Gujal00** [comment]
If it is a fresh install of Linux Mint, you probably have got kodi 19 aka Matrix installed. Resilveurl 5.0.38 is ancient and is written in Python2 which is no longer aupported on Matrix.
You can see that in the log that the depency os not satisfied
You have to install Resolveurl 5.1.x which is coded to work under matrix

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by tetzy** [comment]
Thanks - I stupildy posted too soon...I fixed the error myself.
