### ISSUE TITLE
Dailymotion

### ISSUE THREAD

**Issue by manolischania** [jsergio123/script.module.resolveurl#443]
Hi dailymotion seems cannot resolve. 
Thanks in advance

**Comment by Gujal00** [comment]
Seems to working fine for my test embeds.
If it is not working for you please provide the non working embed

**Comment by Twilight0** [comment]
He must have been using AliveGR, so please state which item/episode/title you 're trying to play. AliveGR's debug logging also shows that. And by the way, on my tests it also works.

**Comment by manolischania** [comment]
Yes i was using alivegr i have wrote you twilight0 what i was searching if you can take a look

**Comment by Twilight0** [comment]
> Yes i was using alivegr i have wrote you twilight0 what i was searching if you can take a look

You didn't tell me which item you 're trying, how am I supposed to know what is going wrong? Try "Χαι Ροκ" episode 1, dailymotion stream for instance, this one plays. I bet what you 're trying to play is a dead link (removed by the user, or via a DMCA claim).

**Comment by manolischania** [comment]
the problem it is in my network or so its seems .. when i start a link with my vpn network ( router vpn) from kodi its not playing but from browser its ok .. when i try from other network the same links work and inside kodi . @twilight0 i thought that you are watching the channel in grecotm for addon alivegr . sorry for my miss understanding .

**Comment by Twilight0** [comment]
> @Twilight0 i thought that you are watching the channel in grecotm for addon alivegr . sorry for my miss understanding .

I can't read, watch and follow every channel about addon discussions, sorry for that.
