### ISSUE TITLE
will it be possible to create a script for this site? redecanaistv.com

### ISSUE THREAD

**Issue by zoreu** [jsergio123/script.module.resolveurl#452]
```
website: redecanaistv.com
link: https://gamesgo.fun/player3/canaishlb.php?canal=bbb21&ads=gamesgo.fun
referer: https://gamesgo.fun/
```

**Comment by Gujal00** [comment]
ResolveURL is generally not for livestreams, those would be under streamlink project

**Comment by zoreu** [comment]
> ResolveURL is generally not for livestreams, those would be under streamlink project

streamlink does not allow import for use in another script

**Comment by Gujal00** [comment]
Use script.module.streamlink which can be imported under other scripts

https://github.com/jairoxyz/script.module.streamlink

Sent from ProtonMail mobile

-------- Original Message --------
