### ISSUE TITLE
hosters list

### ISSUE THREAD

**Issue by caperucitaferoz** [jsergio123/script.module.resolveurl#464]
Is there a way to get a list of all supported hosters?

**Comment by soter80** [comment]
in C:\Users\User\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins

you find all supported hosters

> Is there a way to get a list of all supported hosters?

**Comment by caperucitaferoz** [comment]
Sorry I didn't explain it properly.
I mean a function to obtain data about the supported hosts such as:

- https://api.real-debrid.com/rest/1.0/hosts
- https://api.alldebrid.com/v4/hosts?agent=apiShowcase

**Comment by Gujal00** [comment]
No, there is no such function exposed
you just pass the link to resolveurl.HostedMediaFile(url=link) and see if it is True or False

**Comment by caperucitaferoz** [comment]
And what difference is there between that and doing resolveurl.resolve (url) and checking for result?

**Comment by Gujal00** [comment]
The difference is `resolveurl.HostedMediaFile(url=link)` is instantaneous as it checks if there is a resolver available.
`resolveurl.resolve(url)` on the other hand, actually resolves the url and is slow.
So normal usage is:
```
if resolveurl.HostedMediaFile(link):
    stream_url = resolveurl.resolve(link)
```
