### ISSUE TITLE
Net file

### ISSUE THREAD

**Issue by thecrewwh** [jsergio123/script.module.resolveurl#467]
By adding this it is breaking calling of sites that require 1_2 or above in Kodi 18 
```python
elif six.PY2 or 'android' in kodi.py_ver.lower():
    try:
        import ssl
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1_1)
        if self._http_debug:
            handlers += [urllib_request.HTTPSHandler(context=ctx, debuglevel=1)]
        else:
            handlers += [urllib_request.HTTPSHandler(context=ctx)]
    except:
        pass
```

**Comment by Gujal00** [comment]
Can you please let me know which site is affected. This fix was implemented so that lot of streamers behind cloudflaressl that use cloudflare cert dont work with TLS1.2 in Kodi18 and on Android on Kodi 19

**Comment by thecrewwh** [comment]
Gitlab is affected it requires 1.2 or above to request anything hosted there

**Comment by classymouse** [comment]
there are more, bitbucket also requires 1.2 as of dec. '18

**Comment by Gujal00** [comment]
SMR doesnt talk to bitbucket or gitlab, Are you using a SMR internal utility function directly in your addon?

**Comment by Gujal00** [comment]
@thecrewwh @classymouse 
Can you test with the attached net.py and let me know if it fixes the issue for you. I will work on a general release once you  confirm.

[net.zip](https://github.com/jsergio123/script.module.resolveurl/files/6605590/net.zip)

**Comment by thecrewwh** [comment]
Yes this works perfectly thank you

**Comment by classymouse** [comment]
Working, Thank you Gujal ;)
