### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by Diabolik4411** [jsergio123/script.module.resolveurl#468]
Congratulations on the work you do.  I wanted to point out that these types of links are not read by the resolver, or rather the resolver reads them up to the first number playing another video.

https://streamingcommunity.xyz/watch/2695?e=25889

**Comment by Gujal00** [comment]
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/036dee07ac01a0a3125a780e4fad58823bdc804f
