### ISSUE TITLE
dood not work, any updates?

### ISSUE THREAD

**Issue by beguganjangjr** [jsergio123/script.module.resolveurl#471]
https://dood.to/e/h9ek86a9p35u

**Comment by Gujal00** [comment]
That embed plays fine in smr link tester. If it doesnt work for you paste the full debug log into paste.kodi.tv and provide the link here

**Comment by beguganjangjr** [comment]
nothing matches in html https://ghostbin.co/paste/pr59uw
the html is different

**Comment by Gujal00** [comment]
You seem to have triggered google recaptcha. Cant do anything about it in ResolveURL unfortunately. Try later if your IP has been cleared
This is how the page normally looks https://ghostbin.co/paste/v2jq9k

**Comment by beguganjangjr** [comment]
yes its my ip issues. thanks
