### ISSUE TITLE
Can you add the hydrax(absyy.to) ? 

### ISSUE THREAD

**Issue by lavara123** [jsergio123/script.module.resolveurl#476]
Can you add this?

```sh
curl 'https://embed2.megaxfer.ru/embed2/01bded490f99430277078b8ad5ae9af8' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36' \
  -H 'referer: https://www.2embed.ru/' \
  --compressed
```

**Comment by Gujal00** [comment]
Unfortunately can't be done as Hydrax delivers the stream (segments stored in Google Drive) over websocket instead of any standard Kodi supported streaming protocol. So will only work with their custom player on the webbrowser and not inside Kodi.

**Comment by lavara123** [comment]
> Unfortunately can't be done as Hydrax delivers the stream (segments stored in Google Drive) over websocket instead of any standard Kodi supported streaming protocol. So will only work with their custom player on the webbrowser and not inside Kodi.

There is an old example of what can be done for Kodi, can't this be improved?

https://github.com/L2501/script.gslug.player


https://github.com/L2501/script.gslug.player/blob/master/resources/service/gslug.py

**Comment by Gujal00** [comment]
ResolveURL is not a player, not the right solution
