### ISSUE TITLE
how do i decode this code completely in python?

### ISSUE THREAD

**Issue by zoreu** [jsergio123/script.module.resolveurl#477]
I need to decode javascript to get the broadcast link in kodi

` eval(function(p,a,c,k,e,d) `

**Comment by Gujal00** [comment]
What is the embed url?
It decodes to `https://edge-aws.aovivotv.xyz/hls/s:88.198.163.51/premiereclubes_3f1522d0_86933a89962a58cfb3e26eb4621b543969b8c604/playlist.m3u8?jsf=YTozOntpOjA7czoxMzoiMTcyLjcwLjgyLjEyOSI7aToxO3M6MTE1OiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvOTEuMC40NDcyLjE2NCBTYWZhcmkvNTM3LjM2IjtpOjI7aToxNjI2NzIyMTAyO30=`

**Comment by zoreu** [comment]
i need script decode for make addon, because the url is temporary

**Comment by Gujal00** [comment]
If it is not a embed site that can be added to ResolveURL, then it is not a issue with ResolveURL

**Comment by zoreu** [comment]
I just wanted a python script to break this javascript

**Comment by Gujal00** [comment]
@zoreu Okay, live TV is not a target for ResolveURL

you can use this code for decoding the final url. get jsunpack.py from resolveurl lib folder
```python
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 20 12:03:54 2021

@author: gujal
"""
import jsunpack
import re
import codecs

html = '''eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('q n=r(){};k.y={11:n,1k:n,6V:n,1h:n,D:n,34:n,3A:n,3x:n,3q:n,3p:n,31:n,2L:n,2Z:n,2H:n};(r(){q H;i(k==k.2v){m v}r 2n(){q O=1r.2J.2N.2Q();q 1g;i(O){1g=3m 1r.t.4s({1n:{4J:[\'Q://4A.2a.1o\',\'Q://4G.2a.1o\',\'Q://29.4B.3W\',\'Q://29.3V.45\',]}})}H=2o(\'H\',{43:\'42-41\',3Y:"3E",44:g,4a:4e,3G:4K,1h:v,4y:{4u:v,4h:v,22:{3u:g,3b:g,36:g,4o:g,2x:g},2O:{1h:v,4w:7,1n:O?1g.4L():u.4E.1n,3X:g,2t:g,3Z:-1,40:v,49:1v,4b:30,4c:3F,3U:60*X*X,3T:0.5,3S:2,3R:0.3Q,3P:0.2,3O:10,3N:g,3M:g,3K:3J,3I:10,3H:1P,4f:1z,4g:1v,4z:20,4C:3,4D:1P,4F:1z,4H:20,4M:10,4N:4O,4I:1z,4q:0,4x:g,4j:v,4k:v,4l:5.0,4m:9.0,4n:4.0,4P:15.0,4i:4p,4r:0.8,4t:0.7}}});i(O)1r.t.4v(H);r S(){H.1W({1W:\'//\'+c.d(3D)+c.d(23)+\'\\3C\'+\'e-a\'+c.d(1E)+\'\\2Y\'+c.d(46)+\'2X\'+\'\\2W\'+c.d(1L)+c.d(P)+\'\\2V\'+c.d(R)+c.d(1B)+\'\\2U\'+\'s\\2T\'+c.d(1H)+c.d(58)+\'8\\12\'+\'.19\'+\'8\'+\'\\2S\'+\'16\'+\'3.5\'+\'\\1J\'+c.d(47)+c.d(2q)+\'2R\'+\'2P\'+c.d(2M)+\'e\'+c.d(1t)+\'\\2K\'+\'2C\'+c.d(2I)+\'3\\2w\'+\'\\2y\'+\'2d\\21\'+\'2z\'+c.d(56)+\'6\\2u\'+\'3\'+c.d(51)+\'\\1U\'+\'\\12\'+\'9\\1K\'+\'2B\'+\'\\12\'+\'\\2A\'+c.d(1V)+\'3e\'+c.d(50)+c.d(54)+\'2D\'+\'2E\'+\'\\2F\'+\'\\2G\'+c.d(52)+\'3\\1K\'+\'9\'+\'b\'+\'\\12\'+c.d(1t)+c.d(54)+\'32\'+\'/\'+\'\\1u\'+\'3o\'+\'\\1C\'+\'\\3r\'+\'3s.\'+\'\\3t\'+\'3\'+c.d(1y)+\'8?\\3n\'+c.d(1H)+\'f=\'+\'\\3w\'+\'T\'+\'3y\'+c.d(79)+c.d(3z)+c.d(1L)+\'\\1u\'+c.d(79)+c.d(3B)+\'\\1Z\'+\'3v\'+\'3l\'+c.d(77)+c.d(1B)+\'o\\3k\'+c.d(77)+\'T\\1F\'+c.d(R)+c.d(76)+\'35\'+c.d(1E)+\'37\'+\'\\38\'+\'j\'+\'39\'+c.d(1x)+c.d(73)+\'33\'+c.d(3a)+\'3d\'+\'3f\'+\'3g\'+\'1O\'+c.d(3h)+\'\\3i\'+\'3j\'+c.d(2q)+\'4d\'+\'\\4R\'+c.d(5l)+c.d(1y)+\'\\6S\'+\'\\6R\'+c.d(6Q)+c.d(50)+\'\\6P\'+c.d(1y)+\'Z\\6O\'+c.d(57)+\'3c\'+c.d(R)+\'6N\'+\'V\'+\'C\'+c.d(65)+\'\\6M\'+\'\\6L\'+\'\\1C\'+\'6K\'+\'6J\'+c.d(50)+\'N\\1Q\'+\'6I\\6H\'+\'\\6G\'+c.d(48)+\'K\'+c.d(1x)+\'6E\\1F\'+c.d(72)+c.d(66)+\'6r\'+\'\\1D\'+c.d(6D)+\'Y\\6C\'+\'\\1u\'+c.d(23)+c.d(67)+\'8\\1J\'+\'M\\6B\'+c.d(1t)+\'6A\'+c.d(1N)+c.d(6U)+\'6z\'+\'\\6y\'+\'\\6x\'+\'6w\'+\'\\1Y\'+\'6v\'+c.d(6u)+\'\\6t\'+\'6s\\1D\'+\'l\'+c.d(1N)+\'2\\6T\'+c.d(P)+\'\\6F\'+c.d(1x)+\'B\\1Q\'+\'\\1U\'+\'7a\'+c.d(1V)+\'W\\70\'+c.d(P)+\'6Y\\6W\'+\'\\75\'+c.d(67)+\'4\\6Z\'+\'6X\'+c.d(R)+\'\\71\'+\'74\'+c.d(50)+\'N\\1Y\'+\'\\78\'+\'6q\'+\'h\'+\'5E\'+c.d(P)+\'6o\'+c.d(77)+\'3L\'+\'j\'+c.d(77)+c.d(50)+\'6p\'+\'\\5m\'+\'\\5n\'+\'T\\5o\'+c.d(5p)+\'5q\'+\'I\'+\'5r\'+\'5k\'+\'5s\'+\'\\1Z\'+\'5u\'+\'\\21\'+\'\\5v\'+c.d(68),24:"5w/x-5x",})}S();q t=H.5y;t.18(u.1a.5z,r(){y.11("1o 5A 22.5B 5t 5i 55 5h !");t.18(u.1a.4T,r(1d,p){y.11("4U 4V, 4W "+p.4X.2j+" 4Y 4Z");t.4S.53()})});q A=[];q J;t.18(u.1a.1c,r(1d,p){y.D(\'1c\',1d,p);i(p.1j){1M(p.24){G u.1X.59:y.D("1j 5a 1k 1T, 1S 1R 1m");t.1e();A=[];1I(J);J=25(r(){S()},15*X);U;G u.1X.5b:y.D("1j 1G 1k 1T, 1S 1R 1m");U;5c:y.D("5d 1m");t.1e();U}}2s{1M(p.F){G u.14.5e:G u.14.5f:G u.14.5g:G u.14.5C:i(!A[p.F])A[p.F]=1;y.D(\'1c N\',A[p.F]);i(A[p.F]>=10){y.D(\'5j 5D 5Z, 62 1G\');t.1e();A=[];1I(J);J=25(r(){S()},15*X)}2s{A[p.F]++}U}}})}2m=r(){L 1s=/63/.2r(E.64)&&/69 6a/.2r(E.6b);L 1i=["2h","6c","6d","61","6e","6g","6h","6i","2i","2f","6j",];L 1l=["2e","26","6k","2c","6l","6m",];1f(q 2g 1b 1l){q 2p=1l[2g];i(k[2p]){m g}};1f(q 27 1b 1i){q 28=1i[27];i(k[\'w\'][28]){m g}};1f(q 17 1b k[\'w\']){i(17.6n(/\\$[a-z]6f/)&&k[\'w\'][17][\'5Y\']){m g}}i(k[\'13\']&&k[\'13\'].1q&&k[\'13\'].1q()&&(k[\'13\'].1q()[\'5O\'](\'5X\')!=-1))m g;i(k[\'w\'][\'1p\'][\'1A\'](\'5G\'))m g;i(k[\'w\'][\'1p\'][\'1A\'](\'2b\'))m g;i(k[\'w\'][\'1p\'][\'1A\'](\'5H\'))m g;i(k[\'E\'].2b)m g;i(k.2c)m g;i(k.2e)m g;i(k.5I)m g;i(k.26)m g;i(w.2f)m g;i(w.2h)m g;i(w.2i)m g;i(1s&&k.5J===1v&&E.5K.2j===0)m g;i(1s&&!k.5L)m g;i(E.5M==="")m g;L 1w=v;E.2k&&E.2k.5F({5N:\'5P\'}).5Q(r(2l){i(5R.5S===\'5T\'&&2l.5U===\'5V\'){L 1w=g}});i(1w)m g;m v};i(!2m())5W(2n);k.2o.11(\'4Q\')})();',62,445,'||||||||||||String|fromCharCode|||true||if||window||return|noop||data|let|function||hlsjs|Hls|false|document||console||maxRetryError|||warn|navigator|details|case|player||reconnectTimeout||var|||isP2PSupported|118|wss|121|attachMedia||break|||1000||||log|u0038|external|ErrorDetails|||documentKey|on||Events|in|ERROR|event|reset|for|engine|debug|documentDetectionKeys|fatal|error|windowDetectionKeys|recover|loader|video|documentElement|toString|p2pml|isChrome|99|u0070|undefined|permissionDenied|83|117|64000|getAttribute|122|u0079|u0064|119|u0063|media|115|clearTimeout|u0031|u00396|116|switch|89||2000|u0044|to|try|encountered|u0061|98|src|ErrorTypes|u0043|u0041|10000|u0030|hls|100|type|setTimeout|__nightmare|documentDetectionKey|documentDetectionKeyValue|tracker|swarm|webdriver|callPhantom||_phantom|__selenium_unwrapped|windowDetectionKey|__webdriver_evaluate|__driver_evaluate|length|permissions|permissionStatus|isBot|initPlayer|videojs|windowDetectionKeyValue|112|test|else|autoStartLoad|u0039|top|u00661|handlePartialData|u00352|_|u0063f|2a5|bes|eb4|621|u0062|u0035|profile|95|core|u006cu|timeEnd|114|HybridLoader|hlsjsConfig|mie|isSupported|re|u002e|u002f|u002fhl|u002ex|u0069vo|aov|u0073|assert||time|04|7aT|trace|jc|enableLowInitialPlaylist|Lj|u0067yL|EyO|111|overrideNative||xO||3M6|MTE|105|u004aN|b3p|u0069|ox|new|u006a|la|groupEnd|group|u006ci|st|u006d|handleManifestRedirects|7cz|u0059|dirxml|oz|110|dir|106|u0067|101|auto|600|muted|manifestLoadingRetryDelay|manifestLoadingMaxRetry|5000|manifestLoadingTimeOut||enableSoftwareAES|enableWorker|liveMaxLatencyDurationCount|maxFragLookUpTolerance|01|seekHoleNudgeDuration|maxSeekHole|maxBufferHole|maxBufferSize|sloppyta|com|startFragPrefetch|preload|startPosition|capLevelToPlayerSize|BR|pt|language|controls|co||||defaultAudioCodec|autoplay|maxBufferLength|maxMaxBufferLength|bGx|autoplayAllowed|manifestLoadingMaxRetryTimeout|startLevel|nativeVideoTracks|abrEwmaDefaultEstimate|stretchShortVideoTrack|forceKeyFrameOnDiscontinuity|abrEwmaFastLive|abrEwmaSlowLive|abrEwmaFastVoD|smoothQualityChange|500000|appendErrorMaxRetry|abrBandWidthFactor|Engine|abrBandWidthUpFactor|nativeAudioTracks|initVideoJsContribHlsJsPlayer|liveSyncDurationCount|enableCEA708Captions|html5|levelLoadingTimeOut|vimm|openwebtorrent|levelLoadingMaxRetry|levelLoadingRetryDelay|DefaultConfig|levelLoadingMaxRetryTimeout|fast|fragLoadingTimeOut|fragLoadingMaxRetryTimeout|trackerAnnounce|autoplayRequiresMute|createLoaderClass|fragLoadingMaxRetry|fragLoadingRetryDelay|500|abrEwmaSlowVoD|off|u0068Lz|el_|MANIFEST_PARSED|manifest|loaded|found|levels|quality|level||||play||bound||||NETWORK_ERROR|network|MEDIA_ERROR|default|cannot|LEVEL_LOAD_ERROR|LEVEL_LOAD_TIMEOUT|FRAG_LOAD_ERROR|together|now|Max|Iy|85|u0070Oj|u00497a|u006f|120|Nj|2Nz|MT|are|yO3|u00253|application|mpegURL|tech_|MEDIA_ATTACHED|and|js|FRAG_LOAD_TIMEOUT|errors|cmk|query|selenium|driver|phantom|orientation|plugins|chrome|languages|name|indexOf|notifications|then|Notification|permission|denied|state|prompt|checkAutoplaySupport|Sequentum|cache_|reached||__webdriver_script_func|detach|Chrome|userAgent|||||Google|Inc|vendor|__selenium_evaluate|__webdriver_script_function|__webdriver_script_fn|dc_|__fxdriver_evaluate|__driver_unwrapped|__webdriver_unwrapped|__fxdriver_unwrapped|_selenium|callSelenium|_Selenium_IDE_Recorder|match|NT|Ijt|YWZ|sZV|IE|u0074l|87|Bsa|ML|u0056E1|u0049|KEt|uMz|u007a|u006bt|108|BB|u004b|u0044Y|u0065|sg|aW4|BX|u0034wO|u0078MC|BO|u0047|u006c|86|u0041o|u004dC|u0074|103|info|u0045|Dc|OT|u0030N|u0055|u004c|||jE|u0075M|||u0042T||HJv'.split('|'),0,{}))'''
html = jsunpack.unpack(html).replace("\\'", "'")
items = re.findall(r'src:\s*(.+?),type', html)[0].split('+')
src = [chr(int(re.findall(r'\d+', x)[0])) if 'String.' in x else x.replace("'", "") for x in items]
src = ''.join(src)
src = 'https:' + codecs.decode(src, encoding='unicode_escape')
print(src)
```

**Comment by zoreu** [comment]
> If it is not a embed site that can be added to ResolveURL, then it is not a issue with ResolveURL

I just wanted a python script to break this javascript
website: aovivo.gratis

**Comment by zoreu** [comment]
> @zoreu Okay, live TV is not a target for ResolveURL
> 
> you can use this code for decoding the final url. get jsunpack.py from resolveurl lib folder
> 
> ```python
> # -*- coding: utf-8 -*-
> """
> Created on Tue Jul 20 12:03:54 2021
> 
> @author: gujal
> """
> import jsunpack
> import re
> import codecs
> 
> html = '''eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('q n=r(){};k.y={11:n,1k:n,6V:n,1h:n,D:n,34:n,3A:n,3x:n,3q:n,3p:n,31:n,2L:n,2Z:n,2H:n};(r(){q H;i(k==k.2v){m v}r 2n(){q O=1r.2J.2N.2Q();q 1g;i(O){1g=3m 1r.t.4s({1n:{4J:[\'Q://4A.2a.1o\',\'Q://4G.2a.1o\',\'Q://29.4B.3W\',\'Q://29.3V.45\',]}})}H=2o(\'H\',{43:\'42-41\',3Y:"3E",44:g,4a:4e,3G:4K,1h:v,4y:{4u:v,4h:v,22:{3u:g,3b:g,36:g,4o:g,2x:g},2O:{1h:v,4w:7,1n:O?1g.4L():u.4E.1n,3X:g,2t:g,3Z:-1,40:v,49:1v,4b:30,4c:3F,3U:60*X*X,3T:0.5,3S:2,3R:0.3Q,3P:0.2,3O:10,3N:g,3M:g,3K:3J,3I:10,3H:1P,4f:1z,4g:1v,4z:20,4C:3,4D:1P,4F:1z,4H:20,4M:10,4N:4O,4I:1z,4q:0,4x:g,4j:v,4k:v,4l:5.0,4m:9.0,4n:4.0,4P:15.0,4i:4p,4r:0.8,4t:0.7}}});i(O)1r.t.4v(H);r S(){H.1W({1W:\'//\'+c.d(3D)+c.d(23)+\'\\3C\'+\'e-a\'+c.d(1E)+\'\\2Y\'+c.d(46)+\'2X\'+\'\\2W\'+c.d(1L)+c.d(P)+\'\\2V\'+c.d(R)+c.d(1B)+\'\\2U\'+\'s\\2T\'+c.d(1H)+c.d(58)+\'8\\12\'+\'.19\'+\'8\'+\'\\2S\'+\'16\'+\'3.5\'+\'\\1J\'+c.d(47)+c.d(2q)+\'2R\'+\'2P\'+c.d(2M)+\'e\'+c.d(1t)+\'\\2K\'+\'2C\'+c.d(2I)+\'3\\2w\'+\'\\2y\'+\'2d\\21\'+\'2z\'+c.d(56)+\'6\\2u\'+\'3\'+c.d(51)+\'\\1U\'+\'\\12\'+\'9\\1K\'+\'2B\'+\'\\12\'+\'\\2A\'+c.d(1V)+\'3e\'+c.d(50)+c.d(54)+\'2D\'+\'2E\'+\'\\2F\'+\'\\2G\'+c.d(52)+\'3\\1K\'+\'9\'+\'b\'+\'\\12\'+c.d(1t)+c.d(54)+\'32\'+\'/\'+\'\\1u\'+\'3o\'+\'\\1C\'+\'\\3r\'+\'3s.\'+\'\\3t\'+\'3\'+c.d(1y)+\'8?\\3n\'+c.d(1H)+\'f=\'+\'\\3w\'+\'T\'+\'3y\'+c.d(79)+c.d(3z)+c.d(1L)+\'\\1u\'+c.d(79)+c.d(3B)+\'\\1Z\'+\'3v\'+\'3l\'+c.d(77)+c.d(1B)+\'o\\3k\'+c.d(77)+\'T\\1F\'+c.d(R)+c.d(76)+\'35\'+c.d(1E)+\'37\'+\'\\38\'+\'j\'+\'39\'+c.d(1x)+c.d(73)+\'33\'+c.d(3a)+\'3d\'+\'3f\'+\'3g\'+\'1O\'+c.d(3h)+\'\\3i\'+\'3j\'+c.d(2q)+\'4d\'+\'\\4R\'+c.d(5l)+c.d(1y)+\'\\6S\'+\'\\6R\'+c.d(6Q)+c.d(50)+\'\\6P\'+c.d(1y)+\'Z\\6O\'+c.d(57)+\'3c\'+c.d(R)+\'6N\'+\'V\'+\'C\'+c.d(65)+\'\\6M\'+\'\\6L\'+\'\\1C\'+\'6K\'+\'6J\'+c.d(50)+\'N\\1Q\'+\'6I\\6H\'+\'\\6G\'+c.d(48)+\'K\'+c.d(1x)+\'6E\\1F\'+c.d(72)+c.d(66)+\'6r\'+\'\\1D\'+c.d(6D)+\'Y\\6C\'+\'\\1u\'+c.d(23)+c.d(67)+\'8\\1J\'+\'M\\6B\'+c.d(1t)+\'6A\'+c.d(1N)+c.d(6U)+\'6z\'+\'\\6y\'+\'\\6x\'+\'6w\'+\'\\1Y\'+\'6v\'+c.d(6u)+\'\\6t\'+\'6s\\1D\'+\'l\'+c.d(1N)+\'2\\6T\'+c.d(P)+\'\\6F\'+c.d(1x)+\'B\\1Q\'+\'\\1U\'+\'7a\'+c.d(1V)+\'W\\70\'+c.d(P)+\'6Y\\6W\'+\'\\75\'+c.d(67)+\'4\\6Z\'+\'6X\'+c.d(R)+\'\\71\'+\'74\'+c.d(50)+\'N\\1Y\'+\'\\78\'+\'6q\'+\'h\'+\'5E\'+c.d(P)+\'6o\'+c.d(77)+\'3L\'+\'j\'+c.d(77)+c.d(50)+\'6p\'+\'\\5m\'+\'\\5n\'+\'T\\5o\'+c.d(5p)+\'5q\'+\'I\'+\'5r\'+\'5k\'+\'5s\'+\'\\1Z\'+\'5u\'+\'\\21\'+\'\\5v\'+c.d(68),24:"5w/x-5x",})}S();q t=H.5y;t.18(u.1a.5z,r(){y.11("1o 5A 22.5B 5t 5i 55 5h !");t.18(u.1a.4T,r(1d,p){y.11("4U 4V, 4W "+p.4X.2j+" 4Y 4Z");t.4S.53()})});q A=[];q J;t.18(u.1a.1c,r(1d,p){y.D(\'1c\',1d,p);i(p.1j){1M(p.24){G u.1X.59:y.D("1j 5a 1k 1T, 1S 1R 1m");t.1e();A=[];1I(J);J=25(r(){S()},15*X);U;G u.1X.5b:y.D("1j 1G 1k 1T, 1S 1R 1m");U;5c:y.D("5d 1m");t.1e();U}}2s{1M(p.F){G u.14.5e:G u.14.5f:G u.14.5g:G u.14.5C:i(!A[p.F])A[p.F]=1;y.D(\'1c N\',A[p.F]);i(A[p.F]>=10){y.D(\'5j 5D 5Z, 62 1G\');t.1e();A=[];1I(J);J=25(r(){S()},15*X)}2s{A[p.F]++}U}}})}2m=r(){L 1s=/63/.2r(E.64)&&/69 6a/.2r(E.6b);L 1i=["2h","6c","6d","61","6e","6g","6h","6i","2i","2f","6j",];L 1l=["2e","26","6k","2c","6l","6m",];1f(q 2g 1b 1l){q 2p=1l[2g];i(k[2p]){m g}};1f(q 27 1b 1i){q 28=1i[27];i(k[\'w\'][28]){m g}};1f(q 17 1b k[\'w\']){i(17.6n(/\\$[a-z]6f/)&&k[\'w\'][17][\'5Y\']){m g}}i(k[\'13\']&&k[\'13\'].1q&&k[\'13\'].1q()&&(k[\'13\'].1q()[\'5O\'](\'5X\')!=-1))m g;i(k[\'w\'][\'1p\'][\'1A\'](\'5G\'))m g;i(k[\'w\'][\'1p\'][\'1A\'](\'2b\'))m g;i(k[\'w\'][\'1p\'][\'1A\'](\'5H\'))m g;i(k[\'E\'].2b)m g;i(k.2c)m g;i(k.2e)m g;i(k.5I)m g;i(k.26)m g;i(w.2f)m g;i(w.2h)m g;i(w.2i)m g;i(1s&&k.5J===1v&&E.5K.2j===0)m g;i(1s&&!k.5L)m g;i(E.5M==="")m g;L 1w=v;E.2k&&E.2k.5F({5N:\'5P\'}).5Q(r(2l){i(5R.5S===\'5T\'&&2l.5U===\'5V\'){L 1w=g}});i(1w)m g;m v};i(!2m())5W(2n);k.2o.11(\'4Q\')})();',62,445,'||||||||||||String|fromCharCode|||true||if||window||return|noop||data|let|function||hlsjs|Hls|false|document||console||maxRetryError|||warn|navigator|details|case|player||reconnectTimeout||var|||isP2PSupported|118|wss|121|attachMedia||break|||1000||||log|u0038|external|ErrorDetails|||documentKey|on||Events|in|ERROR|event|reset|for|engine|debug|documentDetectionKeys|fatal|error|windowDetectionKeys|recover|loader|video|documentElement|toString|p2pml|isChrome|99|u0070|undefined|permissionDenied|83|117|64000|getAttribute|122|u0079|u0064|119|u0063|media|115|clearTimeout|u0031|u00396|116|switch|89||2000|u0044|to|try|encountered|u0061|98|src|ErrorTypes|u0043|u0041|10000|u0030|hls|100|type|setTimeout|__nightmare|documentDetectionKey|documentDetectionKeyValue|tracker|swarm|webdriver|callPhantom||_phantom|__selenium_unwrapped|windowDetectionKey|__webdriver_evaluate|__driver_evaluate|length|permissions|permissionStatus|isBot|initPlayer|videojs|windowDetectionKeyValue|112|test|else|autoStartLoad|u0039|top|u00661|handlePartialData|u00352|_|u0063f|2a5|bes|eb4|621|u0062|u0035|profile|95|core|u006cu|timeEnd|114|HybridLoader|hlsjsConfig|mie|isSupported|re|u002e|u002f|u002fhl|u002ex|u0069vo|aov|u0073|assert||time|04|7aT|trace|jc|enableLowInitialPlaylist|Lj|u0067yL|EyO|111|overrideNative||xO||3M6|MTE|105|u004aN|b3p|u0069|ox|new|u006a|la|groupEnd|group|u006ci|st|u006d|handleManifestRedirects|7cz|u0059|dirxml|oz|110|dir|106|u0067|101|auto|600|muted|manifestLoadingRetryDelay|manifestLoadingMaxRetry|5000|manifestLoadingTimeOut||enableSoftwareAES|enableWorker|liveMaxLatencyDurationCount|maxFragLookUpTolerance|01|seekHoleNudgeDuration|maxSeekHole|maxBufferHole|maxBufferSize|sloppyta|com|startFragPrefetch|preload|startPosition|capLevelToPlayerSize|BR|pt|language|controls|co||||defaultAudioCodec|autoplay|maxBufferLength|maxMaxBufferLength|bGx|autoplayAllowed|manifestLoadingMaxRetryTimeout|startLevel|nativeVideoTracks|abrEwmaDefaultEstimate|stretchShortVideoTrack|forceKeyFrameOnDiscontinuity|abrEwmaFastLive|abrEwmaSlowLive|abrEwmaFastVoD|smoothQualityChange|500000|appendErrorMaxRetry|abrBandWidthFactor|Engine|abrBandWidthUpFactor|nativeAudioTracks|initVideoJsContribHlsJsPlayer|liveSyncDurationCount|enableCEA708Captions|html5|levelLoadingTimeOut|vimm|openwebtorrent|levelLoadingMaxRetry|levelLoadingRetryDelay|DefaultConfig|levelLoadingMaxRetryTimeout|fast|fragLoadingTimeOut|fragLoadingMaxRetryTimeout|trackerAnnounce|autoplayRequiresMute|createLoaderClass|fragLoadingMaxRetry|fragLoadingRetryDelay|500|abrEwmaSlowVoD|off|u0068Lz|el_|MANIFEST_PARSED|manifest|loaded|found|levels|quality|level||||play||bound||||NETWORK_ERROR|network|MEDIA_ERROR|default|cannot|LEVEL_LOAD_ERROR|LEVEL_LOAD_TIMEOUT|FRAG_LOAD_ERROR|together|now|Max|Iy|85|u0070Oj|u00497a|u006f|120|Nj|2Nz|MT|are|yO3|u00253|application|mpegURL|tech_|MEDIA_ATTACHED|and|js|FRAG_LOAD_TIMEOUT|errors|cmk|query|selenium|driver|phantom|orientation|plugins|chrome|languages|name|indexOf|notifications|then|Notification|permission|denied|state|prompt|checkAutoplaySupport|Sequentum|cache_|reached||__webdriver_script_func|detach|Chrome|userAgent|||||Google|Inc|vendor|__selenium_evaluate|__webdriver_script_function|__webdriver_script_fn|dc_|__fxdriver_evaluate|__driver_unwrapped|__webdriver_unwrapped|__fxdriver_unwrapped|_selenium|callSelenium|_Selenium_IDE_Recorder|match|NT|Ijt|YWZ|sZV|IE|u0074l|87|Bsa|ML|u0056E1|u0049|KEt|uMz|u007a|u006bt|108|BB|u004b|u0044Y|u0065|sg|aW4|BX|u0034wO|u0078MC|BO|u0047|u006c|86|u0041o|u004dC|u0074|103|info|u0045|Dc|OT|u0030N|u0055|u004c|||jE|u0075M|||u0042T||HJv'.split('|'),0,{}))'''
> html = jsunpack.unpack(html).replace("\\'", "'")
> items = re.findall(r'src:\s*(.+?),type', html)[0].split('+')
> src = [chr(int(re.findall(r'\d+', x)[0])) if 'String.' in x else x.replace("'", "") for x in items]
> src = ''.join(src)
> src = 'https:' + codecs.decode(src, encoding='unicode_escape')
> print(src)
> ```

thank you, be at peace
