### ISSUE TITLE
How to make header "Host:" the first header

### ISSUE THREAD

**Issue by emadmahdi** [jsergio123/script.module.resolveurl#485]
Some video websites started to check headers sequence ... how can i modify the sequence from python ... here is an example of this problem:

=== Resolve perfectly ===
GET   https://dood.la/e/vvdiu7jlpo2o
Host: dood.la
User-Agent: Mozilla/5.0

=== Does not resolve and returns error 403 ===
GET   https://dood.la/e/vvdiu7jlpo2o
User-Agent: Mozilla/5.0
Host: dood.la

**Comment by Gujal00** [comment]
There is no concept of header sequencing, The above link plays fine in SMR Link tester. How are you resolving?

**Comment by emadmahdi** [comment]
I use a software named ... "Progress Telerik Fiddler Web Debugger v5.0" ... It allow me to send raw http requests and that was how i found this issue ... The original video URL is from ... https://live.cima4u.ws:2053/Video/Let+Him+Go+2020-41720.html

============

Anyways ... I was using your KODI addon v5.1.30 and it does not resolve this URL because it send "Host" header at the end ... While v5.1.36  &  37 both were able to resolve it correctly and they both send "Host" header as 1st header.

============

I also noticed that CHROME Browser & EDGE Browser ... they both send "Host" as 1st header ... While MS IE Browser send it as 7th header and all the three browsers are resolving correctly ... which means that the video server "doodstream" is requesting the "Host" header location "sequence" based on the value of "User-Agent".

**Comment by Gujal00** [comment]
Closed as it is working with current release
