### ISSUE TITLE
new host gdriveplayer.to

### ISSUE THREAD

**Issue by zoreu** [jsergio123/script.module.resolveurl#495]
**player 1:**
https://gdriveplayer.to/embed2.php?link=aRvh3Mv7m4DAjLdlexqu8QfJTCuAId5gOTAqyGmTs5bB35awzxB2Bc1wMMaR6tSSVEOAZ328nS2Zbwt%252B%252BnMzfCvG11zLLIFNpjTI33Nh1qm73pe7Ur5YwZAAqTVYHASJaXl8pumy0t%252B2d9lqzgI4UYhJwx8OVUwRdRuTL%252F43ThQmyaiR%252BvQtSn8ngAMjcVCMH6WypyZ8iUR8aiArzHc1r0TB1uGncbrN4zbCHQE%252BcZ5h3g2kRc4u3n6HWrE0usjZg%253D

**player 2:**
https://database.gdriveplayer.us/player.php?imdb=tt1285016

from https://gdriveplayer.to

**Comment by Gujal00** [comment]
Sorry these are not genuine video hosters. They just mask the actual google drive link with obfuscation. If the final google drive link is passed to resolveurl, it will then use gdrive addon to get the playable link and pass it to kodi. as such resolveurl doesnt do anything to do with google drive natively
