### ISSUE TITLE
decode code

### ISSUE THREAD

**Issue by zoreu** [jsergio123/script.module.resolveurl#499]
**could someone tell me a python script to decode this code?**
**I just need the python code that decodes the transmit url**

`    <script>
        eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('F=9(){8 m=/1r/.G(7.O)&&/Q R/.G(7.M);8 j=["C","Z","10","11","V","L","W","T","y","p","S",];8 i=["x","u","P","w","X","12",];l(b B h i){b q=i[B];2(5[q]){4 3}};l(b t h j){b s=j[t];2(5[\'6\'][s]){4 3}};l(b f h 5[\'6\']){2(f.Y(/\\$[a-z]U/)&&5[\'6\'][f][\'N\']){4 3}}2(5[\'d\']&&5[\'d\'].g&&5[\'d\'].g()&&(5[\'d\'].g()[\'14\'](\'15\')!=-1))4 3;2(5[\'6\'][\'n\'][\'o\'](\'1n\'))4 3;2(5[\'6\'][\'n\'][\'o\'](\'v\'))4 3;2(5[\'6\'][\'n\'][\'o\'](\'1o\'))4 3;2(5[\'7\'].v)4 3;2(5.w)4 3;2(5.x)4 3;2(5.1p)4 3;2(5.u)4 3;2(6.p)4 3;2(6.C)4 3;2(6.y)4 3;2(m&&5.1m===1s&&7.1t.1u===0)4 3;2(m&&!5.1v)4 3;2(7.1w==="")4 3;8 k=K;7.r&&7.r.1x({1q:\'1l\'}).1k(9(D){2(1j.1i===\'1h\'&&D.1g===\'1f\'){8 k=3}});2(k)4 3;4 K};9 1e(c){1d.1c(\'1b\',c);8 E=6.I(\'H\')[0].1a.J+\'?c=\'+c;5.19.J=E};6.I(\'H\')[0].18=9(e){e.17();2(!F())A.16(9(){A.13()})}',62,96,'||if|true|return|window|document|navigator|var|function||let|token|external||documentKey|toString|in|windowDetectionKeys|documentDetectionKeys|permissionDenied|for|isChrome|documentElement|getAttribute|__selenium_unwrapped|windowDetectionKeyValue|permissions|documentDetectionKeyValue|documentDetectionKey|__nightmare|webdriver|callPhantom|_phantom|__driver_evaluate||grecaptcha|windowDetectionKey|__webdriver_evaluate|permissionStatus|link|isBot|test|go|getElementsByClassName|href|false|__fxdriver_evaluate|vendor|cache_|userAgent|_selenium|Google|Inc|__fxdriver_unwrapped|__webdriver_unwrapped|dc_|__webdriver_script_fn|__driver_unwrapped|callSelenium|match|__selenium_evaluate|__webdriver_script_function|__webdriver_script_func|_Selenium_IDE_Recorder|execute|indexOf|Sequentum|ready|preventDefault|onclick|location|dataset|Validated|warn|console|onValidate|prompt|state|denied|permission|Notification|then|notifications|orientation|selenium|driver|phantom|name|Chrome|undefined|plugins|length|chrome|languages|query'.split('|'),0,{}))
    </script>`

**Comment by Gujal00** [comment]
Please refrain from polluting ResolveURL git with unrelated questions. This is not a Python help forum
