### ISSUE TITLE
Resolveurl can't open Uptobox url's

### ISSUE THREAD

**Issue by freaktabnl** [jsergio123/script.module.resolveurl#5]
Resolveurl can't open Uptobox url's

ERROR: ResolveURL: ResolverError Error - From: Real-Debrid Link: https://uptobox.com/g3xg38nld2jr: Real Debrid Error: hoster_unavailable (503)
INFO: ZeroconfAndroid: Kodi._airplay._tcp registration removed
INFO: ZeroconfAndroid: Kodi. now registered and active
ERROR: ResolveURL: ResolverError Error - From: uptobox Link: https://uptobox.com/g3xg38nld2jr: File not found

yes, with Realdebrid account activated

**Comment by jsergio123** [comment]
Right now uptobox is on the real-debrid non functional hosters lists. I will look into the free plugin later on.

**Comment by freaktabnl** [comment]
Thanks for the quick reply

**Comment by jsergio123** [comment]
I'm debating on killing off the free plugin while leaving support for debrid services. If there is enough interest I would be willing to implement a plugin for uptobox premium subscribers.

**Comment by freaktabnl** [comment]
Will love that and thanks
