### ISSUE TITLE
Streamtape fail

### ISSUE THREAD

**Issue by zoreu** [jsergio123/script.module.resolveurl#501]
--snip--

`                                              File "C:\Users\Joel\Documents\Kodi18\portable_data\addons\script.module.resolveurl\lib\resolveurl\plugins\streamtape.py", line 43, in get_media_url
                                                raise ResolverError('Video cannot be located.')
                                            ResolverError: Video cannot be located.`

**Comment by Gujal00** [comment]
Please include unedited FULL DEBUG LOG, not snippets
Has been working fine since 5.1.39 release last month. Current release is 5.1.40 and works fine on that too

**Comment by Gujal00** [comment]
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/94e00c262a646d276400b1448b5632564008c5f2
