### ISSUE TITLE
clicknupload error 503

### ISSUE THREAD

**Issue by caperucitaferoz** [jsergio123/script.module.resolveurl#502]
The urls of the videos on this server always return CCurlFile :: FillBuffer - Failed: HTTP returned error 503

**Comment by Gujal00** [comment]
Cant do much as it seems to be a FFMPEG issue. The site is not really a streaming server and seems to have added a header to specifically confuse FFMPEG
ResolveURL gets the correct URL and passes it to Kodi for playback, the response from the server has a header `Content-Range: bytes 0-2681568692/2681568693` for e.g., which is always 1 byte less than the actual file size and that seems to trip FFMPEG
The 503 Error comes when Kodi FFMEG tries to get the last byte

**Comment by populc** [comment]
Ok

**Comment by caperucitaferoz** [comment]
Oh! Wow!!! Anyway thanks for your reply
