### ISSUE TITLE
brfiles

### ISSUE THREAD

**Issue by zoreu** [jsergio123/script.module.resolveurl#508]
https://brfiles.com/f/nqOoy52w/Loucos_por_Justi%C3%A7a_2021_1080p_DUAL_FILMESMEGA.NET.mkv

**Comment by Gujal00** [comment]
Can you give another source, that source seems to be deleted

**Comment by zoreu** [comment]
@Gujal00 working for me, try to use proxy for brazil, maybe that's it

https://brfiles.com/f/qkaBc2Tx/Of%C3%A9lia_2019_1080p_DUAL_FILMESMEGA.NET.mkv

**Comment by Gujal00** [comment]
Sorry I dont have VPN. I get the following message when accessing both the above URLs
```
The requested page could not be displayed.
Here are some possible causes for this error:

     - The requested page does not exist.
     - The requested file has been removed.
     - An unknown error has occurred on our system.
     - You do not have permission to view this page.
     - The server hosting this file may be experiencing technical issues. 
```

**Comment by zoreu** [comment]
@Gujal00 It's an ip lock, I'm going to close the issue
