### ISSUE TITLE
Add animeunity please

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#509]
Hi can you add this host:
hXXps://animeunity.it/anime/12-one-piece/5987

**Comment by Gujal00** [comment]
That is not a video hoster so not a right fit for ResolveURl.
Moreover that page has the streamurl directly so you can use it directly in your addon and no need to send it to resolveurl
`https://server17.streamingaw.online/DDL/ANIME/OnePieceSUBITA/OnePiece_Ep_001_SUB_ITA.mp4`
