### ISSUE TITLE
Feature request: resolve also YouTube playlists and channels

### ISSUE THREAD

**Issue by ostvanc** [jsergio123/script.module.resolveurl#512]
By using the SMR link tester, I have noticed that ResolveURL resolves only URLs for YouTube videos, but no URLs for channels or playlists. Since ResolveURL uses the Kodi addon **plugin.video.youtube**, it would be nice to have this functionality in this library, too.

```
PLUGIN_URL_PREFIX = 'plugin://'
YOUTUBE_PLUGIN_URL = PLUGIN_URL_PREFIX + 'plugin.video.youtube/'
YOUTUBE_PLAY_VIDEO_PLUGIN_URL = YOUTUBE_PLUGIN_URL + 'play/'

YOUTUBE_PLAYLIST_PLUGIN_URL_FORMAT = YOUTUBE_PLUGIN_URL + 'playlist/{}/'
YOUTUBE_CHANNEL_PLUGIN_URL_FORMAT = YOUTUBE_PLUGIN_URL + 'channel/{}/playlists/'

```
See also: [https://kodi.wiki/view/Add-on:YouTube](url)

**Comment by Gujal00** [comment]
ResolveURL is not a scraper looking for multiple videos. Its purpose is to pull out a single playable video when a streamer url is provided. So Unfortunately cant add the above feature to ResolveURL
