### ISSUE TITLE
mega.nz

### ISSUE THREAD

**Issue by zoreu** [jsergio123/script.module.resolveurl#515]
https://mega.nz/file/P5ky3QrS#G2OQ8g_wulySrddmPeXawQnLnGKXuPsdAe7CM1XkLgs

**Comment by Gujal00** [comment]
Mega files are encrypted so one has to get the full file, decrypt it and then pass to kodi. So basically cannot be streamed directly from mega
Hence Mega is only supported through Debrid hosters supported by ResolveURL

**Comment by Twilight0** [comment]
Linksnappy can resolve it for free, consider registering here: https://linksnappy.com
