### ISSUE TITLE
Plz add strtape

### ISSUE THREAD

**Issue by sviet2k** [jsergio123/script.module.resolveurl#532]
Hi @Gujal00,

Can you please add strtape when you have time?
Ex:
h t t p s://strtape.cloud/e/L1WkYPwAXOTbXa

Thanks a lot for your work

**Comment by sviet2k** [comment]
It's a variation of streamtape

**Comment by Gujal00** [comment]
Added in https://github.com/jsergio123/script.module.resolveurl/commit/8d64761837f0fb207bb7f660e45e56b2b017cf65
