### ISSUE TITLE
DoodStream

### ISSUE THREAD

**Issue by dracosc22679** [jsergio123/script.module.resolveurl#533]
DoodStream resolver is not working for some days now. Getting HTTP Error 403: Forbidden error.
I also can't open with python the https://dood.so/e/xxxxxxxxx page, unless i use cfscrape (CloudScraper) and adding 'upgrade-insecure-requests': '1' and 'Cookie': 'cf_clearance=; __cfduid=;' in headers. Please take a look

**Comment by Gujal00** [comment]
It would be regional restriction I presume. There is no issue resolving dood for me. dood.la, doodstream.com and dood.so all work
ResolveURL never had cloudflare bypass functionality and does not include cloudscraper as it is a neverending battle. Have no intentions of including it

**Comment by TheGridRepo** [comment]
it dood.watch the same , or is there no resolver for this https://dood.watch/d/xxxxxxxxxx

**Comment by Gujal00** [comment]
@TheGridRepo
It is already supported by the resolver
```domains = ['dood.watch', 'doodstream.com', 'dood.to', 'dood.so', 'dood.cx', 'dood.la', 'dood.ws']```

**Comment by TheGridRepo** [comment]
yes just notice its supported yes my need fix doesn't seem to be playing.

**Comment by Gujal00** [comment]
@TheGridRepo the link you posted plays fine as long as it doesnt trigger cloudflare captcha in your region. It doesnt use cloudflare captcha everywhere. Check in your browser if you are seeing cloudflare captcha for that. Remember to clear cookies before testing in browser
```
2021-11-05 11:17:19.889 T:664      INFO <general>: SMR Link Tester: Link Resolved: |
https://dood.watch/d/wsfyvvxxxxxx|
https://db89hw.dood.video/u5kj7go6t7hlsdgge6xggjqpdomu4qb7kttxx65ecb7dteac5u7h2dyv2flq/bdfg4iuxit~T4yUgfbA52?token=qb0ic7bc7b87uaradhyjsgq9&expiry=1636064238601|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F84.0.4136.7+Safari%2F537.36&Referer=https%3A%2F%2Fdood.watch%2Fe%2Fwsfyvvxxxxxx|
```
