### ISSUE TITLE
UPTOBOX not working anymore

### ISSUE THREAD

**Issue by zuvedam** [jsergio123/script.module.resolveurl#540]
Hi, just as my alldebrid acc expired, I realized Uptobox is not working as a scraper I even cant play my own Uptobox links by  "Smr link Tester"

**Comment by Gujal00** [comment]
I am getting the following error on the site with my test account (not premium)
```
Streaming status OFF
The streaming server in charge of this file is currently down. Please try again later.
```
So can't fix it inside resolveurl

**Comment by zuvedam** [comment]
@Gujal00  thank you for your great work - just sent you my  premium ACC in case U needed

**Comment by Gujal00** [comment]
Uptobox have switched to multi bitrate HLS for streaming
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/dcfcaab546c0a60422e767b13b3b5e0c44404b66
