### ISSUE TITLE
fplayer stop working

### ISSUE THREAD

**Issue by sviet2k** [jsergio123/script.module.resolveurl#545]
Can you please fix the resolver of fplayer when you have time?

hxxps://f player.info/v/py4ldsmp3q5n6pk

Thanks

**Comment by Gujal00** [comment]
There is nothing wrong with the resolver, the ssl certificate that they are using since 17 Nov is from a new CA that Kodi doesn't trust

**Comment by sviet2k** [comment]
Thanks a lot for your quick answer. You are right. Kodi cannot play but MXPlayer can.
Do you have a work around to play this link with Kodi? Ex: add verifypeer=false in the header to bypass the ssl verification.
If  yes, please share with me and I will implement it in my addon.
Thanks

**Comment by solbu** [comment]
There is an official Kodi guide on how to do this:
https://kodi.wiki/view/SSL_certificates

**Comment by sviet2k** [comment]
Thanks @solbu for the hint but the fix is on the Android or PC machine. I would like to have a 'global' fix in my addon.

**Comment by shellc0de27** [comment]
@sviet2k See the latest pull request :)

**Comment by sviet2k** [comment]
Thanks @shellc0de27.
Add the verifypeer in the header will fix the problem.
