### ISSUE TITLE
Resolver request

### ISSUE THREAD

**Issue by kingul** [jsergio123/script.module.resolveurl#550]
Hi, can you make resolver for this link: https:// www .rovideo .net/embed/17145
the real link is inside html code: "link href="https :// www .rovideo.net/videos/17145/cavaler-accidental-unchiul-arnolf-sezonul-3-episodul-9/)"

**Comment by Gujal00** [comment]
Added in https://github.com/jsergio123/script.module.resolveurl/commit/0dd090a3f0a7f164529d2d457ba6cb8ab91e93b2

**Comment by kingul** [comment]
Thank you!
