### ISSUE TITLE
Supervideo not work 

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#565]
Hi guy supervideo not works on kodi returned error http 404, like file not exists, but in Brower page works fine.
Link: hxxps://supervideo.tv/e/n8ib4y4e039g

**Comment by Gujal00** [comment]
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/d2101468b17b66d3b5838fd75ac5a8f357cf4a9b
