### ISSUE TITLE
i need fix pandafiles

### ISSUE THREAD

**Issue by zoreu** [jsergio123/script.module.resolveurl#566]
i need fix
https://pandafiles.com/yacdjkyz3i65/Ghostbusters.Mais.Alem.2021.720P.Dub.Filmesmp4.com.mp4

**Comment by Gujal00** [comment]
Dont see an issue with ResolveURL. It is resolving correctly and providing the link to Kodi
The file is taking too long on the website for playback which exceeds Kodi's timeout

**Comment by zoreu** [comment]
ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file

**Comment by Gujal00** [comment]
Yes, as i said resolveurl has done its job and sent the url to kodiplayer. The site is too slow and kodiplayer times out. Go to the website in a browser and see for yourself how long it takes before playback starts

**Comment by zoreu** [comment]
I corrected the part
https://paste.kodi.tv/iyosawajik

**Comment by Gujal00** [comment]
updated as per your code in https://github.com/jsergio123/script.module.resolveurl/commit/7933ff683526590fa40426e0ceadda9eee606b58
Please test, For me the site is still too slow and doesnt work

**Comment by zoreu** [comment]
> updated as per your code in [7933ff6](https://github.com/jsergio123/script.module.resolveurl/commit/7933ff683526590fa40426e0ceadda9eee606b58) Please test, For me the site is still too slow and doesnt work

the site is really slow to open, but it worked here, with the resolveurl

**Comment by Gujal00** [comment]
Thanks I will release a ResolveURL update soon
