### ISSUE TITLE
Please can add new host ilgeniodellostreaming

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#567]
Hy guy can you add thi new host?

hxxps://ilgeniodellostreaming.re/film/the-cave-discesa-mortale-streaming/

**Comment by azzy9** [comment]
Hi, that site does not seem to be a host.
It seems to redirect to get videos from tapecontent.net which is steamtape

**Comment by Gujal00** [comment]
Correct resolveurl in only for resolving hoster urls and not embedder urls
