### ISSUE TITLE
New host request 

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl#584]
Hy guy I've a different request, for this time, the site I asked you add, is a sport streaming site.
Link is:
Embedded link hxxps://daddylive.me/embed/stream-114.php
Stream link:
hxxps://daddylive.me/stream/stream-114.php.
Can you add to resolver?

**Comment by Gujal00** [comment]
Livestreaming is not a target for ResolveURL. 
Streamlink is the project that tackles livestreams, so please raise your request in their git
https://github.com/streamlink/streamlink
