### ISSUE TITLE
help me decode a script

### ISSUE THREAD

**Issue by zoreu** [jsergio123/script.module.resolveurl#587]
I searched the internet and didn't find how to break it
I wanted to know a code to get the streaming url
<- snip ->

**Comment by shellc0de27** [comment]
LMAO! Short term memory loss? This is NOT a resolveurl issue and you were told very nicely to stop on Aug. 28th

**Comment by Gujal00** [comment]
Please refrain from polluting ResolveURL git with unrelated questions. This is not a Python help forum
