### ISSUE TITLE
uptobox

### ISSUE THREAD

**Issue by Espinete** [jsergio123/script.module.resolveurl#592]
When I want to see a movie on the uptobox server, when I click the link from kodi, the little sign to link account with a code appears, with that code I link my uptobox account and in kodi after linking my account, it disappears in addition to the typical poster of Kodi that says loading (bottom right), because from here it does not happen after a while like this, it does not launch the movie and the loading poster disappears, could you please solve it thanks.

**Comment by Gujal00** [comment]
What version of ResolveURL is installed in your system?

**Comment by Espinete** [comment]
my version is 5.1.55

**Comment by Gujal00** [comment]
I dont see any issue with the test embed I have.
![image](https://i.imgur.com/dpjUdyU.png)
```
INFO <general>: SMR Link Tester: Link Resolved: |https://uptobox.com/69p85y1omf51|https://www62.uptostream.com/stream/4flx7jc05c/_m_main_0.m3u8|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F84.0.4136.7+Safari%2F537.36|
```
So most probably the link that you are using is dead. If not please provide a full debug log to see what is happening

**Comment by Espinete** [comment]
this is the code that I use for uptobox:
```xml
<item>
<title>prueba7</title>
<urlsolve>https://uptobox.com/69p85y1omf51|https://www62.uptostream.com/stream/4flx7jc05c/_m_main_0.m3u8|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F84.0.4136.7+Safari%2F537.36|</urlsolve>
<thumbnail></thumbnail>
<fanart></fanart>
</item>
```
I can't do the test with your link because uotobox tells me:
You have reached 150 minutes of free viewing as a registered user
therefore you will not see anything in the .log

**Comment by Espinete** [comment]
![liunar](https://user-images.githubusercontent.com/18357275/147396915-063df069-7b31-4bf1-8dca-c3412b0a1adb.PNG)

the code disappeared that's why I take a picture of the code

**Comment by Gujal00** [comment]
Yep, so the resolver did its job, and you are not having a premium uptobox account. Cant do anything about it in ResolveURL as you have exceeded the free limit for the day

**Comment by Espinete** [comment]
when I don't have the restriction on the server, I'll try again with your link, and if kodi can't show me the content I'll send you the .log. Thank you very much for your attention, we keep in touch
