### ISSUE TITLE
uptobox does not release the movie

### ISSUE THREAD

**Issue by Espinete** [jsergio123/script.module.resolveurl#595]
When I want to watch a movie on the uptobox server, when I click on the kodi link, the small sign to link the account with a code appears, with that code I link my uptobox account and in kodi after linking my account, it disappears In addition to the typical Kodi poster that says loading (bottom right), because from here it does not happen, after a while like that, it does not launch the movie and the loading poster disappears.

I have installed the smr_link_tester addon and it does the same from the same addon, everything is correct but when it is time to put the movie it does not launch the movie.

I want to say that my kodi is kodi 18.8 in windows, I will also send you the .log

[kodi.log](https://github.com/jsergio123/script.module.resolveurl/files/7779990/kodi.log)

**Comment by Espinete** [comment]
I'm going crazy with this issue, it turns out that in kodi 19 it works perfectly, but in kodi 18 it does not launch the movie, please could you help me.

**Comment by Gujal00** [comment]
Kodi 18 uses a quite old version of FFMPEG and OpenSSL which may not be compatible with uptobox
`FFmpeg version/source: 4.0.4-Kodi`
`OpenSSL 1.0.2j  26 Sep 2016`

Kodi 19 uses a newer version and plays fine
`FFmpeg version/source: 4.3.2-Kodi`
`OpenSSL 1.1.1d  10 Sep 2019`

In both cases ResolveUrl resolves the uptobox link correctly and passes it to KodiPlayer. So nothing can be done in ResolveUrl to fix this

Update: If you still want to stick with Kodi18, you can configure kodi to use external player and that could work
