### ISSUE TITLE
flashx.tv pairing fails

### ISSUE THREAD

**Issue by sraedler** [jsergio123/script.module.resolveurl#6]
Flashx.tv pairing does not work anymore

the reason is on flashx.cc pairing, it's redirected to flashx.tv

but checking flashx.cc cause no pairing and flashx.tv is pairing legit.

**Comment by jsergio123** [comment]
ok ty

**Comment by jsergio123** [comment]
@sraedler can you please test and confirm these changes. Thank you. https://github.com/jsergio123/script.module.resolveurl/commit/a4acd911165ae626c7e5214ff94d516a0f9fc30e

**Comment by sraedler** [comment]
I hopefully have time on Sunday.

**Comment by sraedler** [comment]
It's not working, sorry
