### ISSUE TITLE
Streamango

### ISSUE THREAD

**Issue by bjgood** [jsergio123/script.module.resolveurl#60]
Hi JSergio,
It may be my system but since you've added this to streamango...

@classmethod
def isPopup(self):
      return True

I don't receive any links (that play) when I do a scan. Streamango doesn't have any popups (like in openload or vshare). Shouldn't that be return False? I switched back to an older version and it works fine.

Thanks, JSergio, for all your hard efforts (I won't call it "work" since you obviously love doing this...:D). They're very much appreciated.

Have a good one.

:)

**Comment by jsergio123** [comment]
You're most likely missing something. Streamango will now fail back to pairing for some links that can't be resolved.

**Comment by jsergio123** [comment]
You need all these file changes 26149f23ad3c4e918c1c3a6e825862a9e0e3e952

**Comment by bjgood** [comment]
I downloaded the whole folder (as a zip file) that contained the new streamango.py plus the files you referenced. I could have done something wrong, I suppose. I'll give it another shot and see what happens.

Thanks for the reply, Jsergio. :).

**Comment by bjgood** [comment]
Just now I downloaded the script.module.resolveurl repo as a zip file...installed it...scanned a tv series...from the results I chose a streamango link...the activities icon spun a couple of times then stopped. No video played. From within the zip file at streamango.py I changed return True to return False...installed that zip file...scanned the same tv series...chose the same streamango link...and it played.

I'm just reporting what I found. Maybe you could check it out? I would be nice if someone else could confirm this.

Just trying to help.

Thanks, JSergio. :).

**Comment by jsergio123** [comment]
Sounds like the addon you are using is disabling resolvers that use pop-ups. Also the source code does not include the settings.xml which needs to be build with every update.

**Comment by bjgood** [comment]
You the man, JSergio. I'm sure you're right about this problem I was trying to report. I'll close this issue now.

Thanks, again for your help and patience.

Best regards. :).
