### ISSUE TITLE
Streamsb stop working

### ISSUE THREAD

**Issue by sviet2k** [jsergio123/script.module.resolveurl#612]
Hi @Gujal00 ,

The streamsb stop working.
The 'download link' does not return the href in the response :(.
Can you please fix it when you have time?
hxxps://streamsb.net/embed-h4fg8eh792ff.html

Thank you,

**Comment by Gujal00** [comment]
Yes that particular one has downloads disabled on the website itself.
Is it happening for all embeds?

**Comment by sviet2k** [comment]
Also for watchsb .Don't know other embeds. I will try to find other link
But I think download is not disabled only a newer way to hide the dl link.

**Comment by shellc0de27** [comment]
@Gujal00 based off what I'm seeing, may need to modify girc a little to capture that token...i think :P

**Comment by Gujal00** [comment]
Fixed in #614 

Update: Something changed again on site and is broken again

**Comment by shellc0de27** [comment]
@Gujal00 What do think about trying this....

use your idea of base64 module, but chop off any extra unnecessary shit at the end after the encoding
`domain = base64.b64encode((rurl[:-1] + ':443').encode('utf-8'))`
`domain = re.sub(r'\W', '', domain)`

does that help?

**Comment by shellc0de27** [comment]
Seems like the `=` is never needed for those api calls. Only ever seen a `.` at the end of the string
Not sure if they replace the = with the . however, leaving it all off works too

**Comment by Gujal00** [comment]
This seems to work
```python
domain = base64.b64encode((rurl[:-1] + ':443').encode('utf-8')).decode('utf-8').replace('=', '')
```

**Comment by shellc0de27** [comment]
awesome let me test real quick

**Comment by shellc0de27** [comment]
perfect works :)

**Comment by Gujal00** [comment]
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/51dd70baa04f9e871b5d7bd80c238553359b6c35

**Comment by sviet2k** [comment]
Hi,

Can you please double check the sbplay2? It seems it does not work.
hxxps://sbplay2.com/e/6ndvw265eiyx

Thank you.
