### ISSUE TITLE
sbplay2 problem

### ISSUE THREAD

**Issue by sviet2k** [jsergio123/script.module.resolveurl#617]
Hi,

Can you please double-check the sbplay2? It seems it does not work.
hxxps://sbplay2.com/e/6ndvw265eiyx

Thank you.

**Comment by Gujal00** [comment]
plays fine for me in ResolveURL 5.1.58. test the embed in smr link tester addon

**Comment by sviet2k** [comment]
Thanks for quick answer. Sorry to disturb you for nothing.

**Comment by Gujal00** [comment]
No problem, reports are good, do keep reporting when you find issues. Thanks
