### ISSUE TITLE
[Need help] Cannot resolve sbplay2

### ISSUE THREAD

**Issue by sviet2k** [jsergio123/script.module.resolveurl#618]
Hi @Gujal00,

I develop a small add-on calling your ResolveUrl  5.1.58.
The add-on can get successfully links (Ex: mixdrop, fembed ...) but cannot with sbplay2 (streamsb)
hxxps://sbplay2.com/e/ae2ybhaq65wp.
Do I need to change the "/e/" to "/d/" to satisfy the get_url?
Can you please help me to implement correctly this when you have time?

Here is the resolve log:
https://pastebin.com/pTUJqC6G

Thank you

**Comment by Gujal00** [comment]
It plays fine regardless of `/d`, `/e/` or `/play/`. Try that link in your browser and see if you are triggering any cloudflare protection. From where I am testing it is fine.

![image](https://i.imgur.com/coB17ox.png)

**Comment by sviet2k** [comment]
Hi @Gujal00,

I can play the video in  browser.

Here are values from debug from Android: (Do you test the link on Windows or Android)

Token: 03AGdBq27QVIzQh7Z6yjucADwPcWx1VTBbL_Fv-vVh67rRFG35RaynNw0taQ01Mohlt7hh1tm9hw-tq1mJSQB4u2QNaIKmYIgeLoKQFemRHuy_NOGMPLzjb8Td6AjWTY9M1De2DP7vhVbXFbckozC_Tm0RmGll-p7dJJAQ4p6vrk5dONnKVuOeD5EX8qnIZfkHcrqcHr6YENuwdKZ9afa6y2ZpYDgL-lx5rm2BLn40cFcDX94Wctw3YpYVZJY_2rTnruf1DdZBIgcCKJDTCv3h8h_d6k4G2R7VCvINQEHCJuS4AMxf3B0Iews91PnDPYkg8XiMQ2gfw8CZpi9WTPc_jEnJdipZniKNG_DDEGCUw81R8eD5eHW_J1n7aEUeNApLex0Y9FtiwSWgFxqZKatYCHJU06es_AALuQ
2022-01-17 19:55:40.339 T:13143   DEBUG <general>: ResolveURL: Domain: aHR0cHM6Ly9zYnBsYXkyLmNvbTo0NDM
2022-01-17 19:55:40.340 T:13143   DEBUG <general>: ResolveURL: rurl: https://sbplay2.com/

dl_url: https://sbplay2.com/dl?op=download_orig&id=it36do4m8tiq&mode=h&hash=8313523-174-89-1642467340-9d7f8c1302af1176647c3286ade1786e

But the response from POST does not contain the "Direct" keyword then raise exception "Video not found"
Please see https://pastebin.com/pTUJqC6G for more details.

the real link:
hxxps://sbplay2.com/d/it36do4m8tiq?caption_1=hxxps://msubload.com/sub/loki-season-1-episode-6-for-all-time-always/loki-season-1-episode-6-for-all-time-always.vtt&sub_1=English

Thanks again for your help

Note: Length of token is different between the Resolve and the browser in debug mode

**Comment by Gujal00** [comment]
Plays fine on Android 9.0 Kodi 19.3

**Comment by sviet2k** [comment]
Hi @Gujal00,

Still have problem to resolve the link :(
If you have time, can you please share with following values:

dl_url: 
hxxps://sbplay2.com/dl?op=download_orig&id=it36do4m8tiq&mode=h&hash=8313523-174-89-1642467340-9d7f8c1302af1176647c3286ade1786e

domain:
aHR0cHM6Ly9zYnBsYXkyLmNvbTo0NDM

token:
03AGdBq27QVIzQh7Z6yjucADwPcWx1VTBbL_Fv-vVh67rRFG35RaynNw0taQ01Mohlt7hh1tm9hw-tq1mJSQB4u2QNaIKmYIgeLoKQFemRHuy_NOGMPLzjb8Td6AjWTY9M1De2DP7vhVbXFbckozC_Tm0RmGll-p7dJJAQ4p6vrk5dONnKVuOeD5EX8qnIZfkHcrqcHr6YENuwdKZ9afa6y2ZpYDgL-lx5rm2BLn40cFcDX94Wctw3YpYVZJY_2rTnruf1DdZBIgcCKJDTCv3h8h_d6k4G2R7VCvINQEHCJuS4AMxf3B0Iews91PnDPYkg8XiMQ2gfw8CZpi9WTPc_jEnJdipZniKNG_DDEGCUw81R8eD5eHW_J1n7aEUeNApLex0Y9FtiwSWgFxqZKatYCHJU06es_AALuQ

I will compare your values with mine.

Again thanks for your time and help

**Comment by shellc0de27** [comment]
@sviet2k you really can't compare these values. Both the hash value from the `dl_url` and `token` are dynamic and changes with each request

**Comment by sviet2k** [comment]
Thanks @shellc0de27  for info.
Any hints for me how to trouble shoot this issue?
Note: the length of token is different between my debug and the Browser debug.

**Comment by shellc0de27** [comment]
Yeah no problem. Honestly i don't know at the moment. Last time i tested that domain, it worked fine. And when it didn't, the server would error out with a 523 response code

**Comment by sviet2k** [comment]
I don't know if I did it correctly, but the SMR link tester gave me "Video not found" for the link hxxps://sbplay2.com/d/it36do4m8tiq

Edit:
Strange problem. This morning SMR tester can resolve the link 3,4 times then stop working after.
It seems there is a limit somewhere.
Do you have the same issue?

Thanks

**Comment by Gujal00** [comment]
sbplay2 uses google invisible recaptcha and may be triggering captcha when tried frequently causing the issue

**Comment by sviet2k** [comment]
It makes sense @Gujal00 
Then we can only resolve 3,4 links per day? Any workaround?
Thank you

**Comment by Gujal00** [comment]
Cannot bypass google captcha.
