### ISSUE TITLE
waaw resolver not working

### ISSUE THREAD

**Issue by kingul** [jsergio123/script.module.resolveurl#63]
Hi, waaw resolver is not working for about a month, can you fix it, please?

**Comment by Gujal00** [comment]
Waaw/Netu/HQQ recently banned a lot of ip addresses, just check if your ip is banned on the webserver by browsing the embed link on your browser. This is mine for example when Browsing to [IP Check Link](https://hqq.tv/player/ip.php)
![Screenshot](https://i.imgur.com/c1RNg15.png)

**Comment by kingul** [comment]
My ip is not banned. You can check it for example on embeded site, because they have protection for direct access from the begining : www. filmeserialeonline. org/episodul/the-witchfinders/
 
The first part from addon works, it's decoding ok, the next step is the problem, md5 player link is not returning anything (maybe some other verifications)

**Comment by jsergio123** [comment]
The resolver is broken and they have my VPN blocked as well so I can't debug it.

**Comment by kingul** [comment]
I used fiddler and also got one ip banned, do you have any other debug method?

PS  there is one more option: to ban as many ips as I could use so nobody use netu to upload videos :)

**Comment by kingul** [comment]
Tried again with firefox debugger and saved the results as har : 
https://filehost.net/46a754d9d731dcb0
Who wants to try can import that file in debugger.

**Comment by Gujal00** [comment]
They are now employing Google Recaptcha v3, and cant be scraped

**Comment by kingul** [comment]
Thank you, all!
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/4a4170a2667a461fc31b0f5e506d0191ea1b5608
