### ISSUE TITLE
After last update addons seem to not work, uptobox asks for a pin too.

### ISSUE THREAD

**Issue by cg00001** [jsergio123/script.module.resolveurl#637]
Some friends asked me, and I read several peeps had this issue too.
Reauthorizing RD on ResolveURL worked for me, a friend mentioned he has to reauthorize daily.

**Comment by Gujal00** [comment]
Please do not use this repo for reporting issues. It is not looked at and is retired
reauth issue fixed in latest release
uptobox is a premium hoster and requires pin if not supported by RD
