### ISSUE TITLE
Vidzi problems

### ISSUE THREAD

**Issue by bjgood** [jsergio123/script.module.resolveurl#65]
Hey JSergio,
For the past long while any vidzi links that show up in a scan do not open. Again, it could be my system. Do vidzi links work for you (or anyone else)?

Happy holidays to you and yours, JSergio. :).

**Comment by jsergio123** [comment]
Are you able to play anything directly from their website? All their videos just hang on loading for me.

**Comment by bjgood** [comment]
Hi JSergio,
I tried a link through a source that used vidzi for a video episode of Death in Paradise and it would not play. It just kept on trying to load. I had uBlock Origin enabled in Firefox. Without uBlock enabled I was bombarded by popups (mainly porn). Impossible situation.

Like you suggest it's probably vidzi itself.

Thanks, JSergio, for your time. You're a great fellow.

Happy holidays to you and yours. :).

I'll close this issue now.

Thanks, again.
