### ISSUE TITLE
New resolveurl 5.0.25 update

### ISSUE THREAD

**Issue by aconer81** [jsergio123/script.module.resolveurl#70]
Hey first of thanks 4 all ur hard work bud really appreciate it 👍
Earlier when the resolveurl updated 2 new 5.0.25 version I tried 2 playing some torrent & magnet links but now it isn’t trying 2 download them it skips the links & I believe it is only playing cached links and I didn’t enable the new option 2 allow cached torrents only! I wanted 2 c if there was an issue on my end so I downgraded back 2 ver. 5.0.24 and then tried playing same movie links and it was working again resolveurl started downloading and and the screen saying resolve url Real Debrid transfer saving item to cloud came up again but with the new update that screen doesn’t come up anymore and a bunch of movie links just get skipped until it finds a cached one or other playable link from a hoster! 
I dunno if this is the way it’s meant 2 be now thanks 4 everything appreciate any feedback have a good one

**Comment by aconer81** [comment]
https://paste.kodi.tv/idonurikob 
Here u go bud hope u can help me out with da issue with this log kuz I can’t play a magnet or torrent link unless it’s already cached nd a lot of older movies aren’t thanks 4 all your hard work really appreciate I luv this new feature and would luv 2 keep using it have a good one

**Comment by aconer81** [comment]
Yes I realized I had that issue and I cleared all the active downloads I had but after i cleared them the resolveurl is still not showing the dialogue screen that pops up saying resolve url Real Debrid transfer and saving torrent to Real Debrid cloud instead when I click on a noncached link it just shows that link for a while like its trying to play it but after about 2 minutes it skips it and it keeps skipping links until it either finds a cached link or playable hoster link!
The funny thing is that I think it does try to download the torrent and save it to Real Debrid that’s how I ended up with so many active downloads! The issue is that the dialogue screen that used to pop up saying taking that it was downloading and showed the file size speed peers & percentage completed is not popping up anymore so I can’t cancel it from there if I wanted to like before so all those links that the script skips end up accumulating to a bunch of active downloads thanks

**Comment by jsergio123** [comment]
I think I see your problem. It might be due to me removing the jarvis skin for the dialog window.

**Comment by aconer81** [comment]
Trying it out now clicked on a from dusk till dawn torrent link about 2gb & so far so good the dialogue screen finally popped up & it’s downloading the movie! 
Thanks so much 4 replying 2 my issue & 4 helping me out really appreciate all the hard work u put in bud have a good day
