### ISSUE TITLE
How to handle Google's reCaptcha?

### ISSUE THREAD

**Issue by doko-desuka** [jsergio123/script.module.resolveurl#71]
Hi,
I noticed that some video hosts and aggregator websites are starting more and more to use Google's reCaptcha.
There's no (sane) way around it other than to manually solve it, but the problem is finding a way for Kodi to use the token obtained after solving it to continue with the scraping.

I tried to find a way to extract the reCaptcha <iframe> element to a blank page where the user could manually solve it (so the add-on could call the browser on this page for the user to solve it, then go back to Kodi), but I hit a dead end where the <iframe> needs to run on the exact same domain it was "registered" to because of browser security policies, otherwise it fails.
If the user is logged into their Google account (doesn't need to be their primary one, it could be a dummy one just for this), the reCaptcha sees the cookies for this and doesn't block you.

Anyway, any ideas on how to best deal with this are welcome.

**Comment by jsergio123** [comment]
message me on keybase
