### ISSUE TITLE
Add Support

### ISSUE THREAD

**Issue by Thor4201** [jsergio123/script.module.resolveurl#74]
would it be possible to add support for Orion Torrents and usenet, They have a a lot to offer https://orionoid.com/ if need more info let me know :)

**Comment by Gujal00** [comment]
Resolveurl is not a scraper, that task is performed by whatever addons you use. Once the addon gets the torrent/magnet it can then pass it to ResolveUrl to play using RD or PM subscription.
ResolveUrl does not have any torrent engine such pulsar, quasar, etc., it simply uses RD or PM to check if the torrent is in their cache and plays the http(s) stream of the files from RD or PM
