### ISSUE TITLE
The current «.gitattributes» results in file changes by simply cloning the repo 

### ISSUE THREAD

**Issue by solbu** [jsergio123/script.module.resolveurl#75]
Hi.
I have a cloned copy of your repo, as do others.

Two files are modified simply by cloning the repo, and I believe the «* text=auto» in «.gitattributes» is the culprit.

> [solbu@solbu-1 ~/tmp/del]$ git clone git@github.com:jsergio123/script.module.resolveurl.git
> Cloning into 'script.module.resolveurl'...
> <cut standard terminal noise>
> [solbu@solbu-1 ~/tmp/del]$ cd script.module.resolveurl/
> [solbu@solbu-1 ~/tmp/del/script.module.resolveurl]$ git status
> On branch master
> Your branch is up-to-date with 'origin/master'.
> Changes not staged for commit:
>         modified:   lib/resolveurl/plugins/myupload.py
>         modified:   lib/resolveurl/plugins/streamcloudco.py

When I do a «git diff» I can't see any visual difference.
When i comment out the «* text=auto» in «.gitattributes», git does not report any changes. (Besides the new change I made in «.gitattributes».)

It might be that this only show up on unix-like systems, such as GNU/Linux which I use.
I only use GNU/Linux, both at home and at work.

**Comment by jsergio123** [comment]
you want me to remove the LF normalization?

**Comment by solbu** [comment]
Sorry, I forgot about this issue.

Removing the line in .gitattributes fixes my issue, if that is what you mean by normalization.
So, yes.

**Comment by Gujal00** [comment]
fixed
