### ISSUE TITLE
RD

### ISSUE THREAD

**Issue by poortuga** [jsergio123/script.module.resolveurl#76]
Hi
I'm trying to use real debrid,for example on openload but it takes me to the pop up pair..
using like this
link = resolveurl.HostedMediaFile(url=Url)
        if link.valid_url():
            stream_url = link.resolve()
Do I need to change anything?
Thanks

**Comment by Gujal00** [comment]
Yes, in SMR universal resolvers, set the priority of RealDebrid to 80 (instead of default 100)

**Comment by jsergio123** [comment]
@poortuga did @Gujal00 's answer resolve you issue?

**Comment by Gujal00** [comment]
@poortuga Did you restart Kodi after changing the priority? There is no other configuration to be done in SMR

**Comment by poortuga** [comment]
@Gujal00  Thanks,now i restart the kodi and woks perfectly..
thanks for the help

**Comment by Gujal00** [comment]
@poortuga Can you please close the issue, now that it is working for you

**Comment by poortuga** [comment]
OK, thanks for the help..
