### ISSUE TITLE
resolveurl 

### ISSUE THREAD

**Issue by TheGridRepo** [jsergio123/script.module.resolveurl#80]
Hi mate notice theres new resolver's and openload and a few other!!! have the latest 5.0.26 yet don't see the changes in that version... or are they still in testing... if so will patiently wait for the next updated showing the new changes made. hope all is well keep up the great work for the community.

**Comment by jsergio123** [comment]
You can see the commit made to this project here https://github.com/jsergio123/script.module.resolveurl/commits/master

Everything after the bump is not included in my latest update.
