### ISSUE TITLE
new resolver mystream.cz behind CF

### ISSUE THREAD

**Issue by Philps** [jsergio123/script.module.resolveurl#84]
Seems to be a direct Stream but hide behind a CF

ExampleURL: https://pastebin.com/yiCk5jpz

**Comment by doko-desuka** [comment]
@jsergio123 I ported Team Universal's CF solver to ResolveURL, see here:  
https://github.com/doko-desuka/script.module.resolveurl/blob/master/lib/resolveurl/plugins/lib/cfsolver.py

**Comment by jsergio123** [comment]
I'll take a look

**Comment by Philps** [comment]
lmk, if a example URL is required, as the pastebin link has expired
