### ISSUE TITLE
Speedvid not resolving

### ISSUE THREAD

**Issue by pinoytracker** [jsergio123/script.module.resolveurl#85]
Hi Jsergio,
seems speedvid is not resolving
sample link#
https://www.speedvid.net/embed-ir4cgn9yngcl-865x530.html
https://www.speedvid.net/embed-fprehmj1ham0-865x530.html

**Comment by jsergio123** [comment]
This host requires daily updates. I have given up on this host at the moment unless there is big enough request for it.

**Comment by bjgood** [comment]
Hi JSergio,
Good to see you back from your break. :).

It would be nice to see speedvid working again. It's one of the best for providing good working links. Hopefully you can get it working again. I wouldn't ask, but I have so few hosts that show up during a scan.

You said it requires daily updates to keep it up. Do they change the code everyday at speedvid dot net? Rather extreme on their part, isn't it?

Thanks for all your hard work on resolveurl, JSergio. It is very much appreciated.

Thanks, buddy. :).

**Comment by jewbmx** [comment]
I just did a little looking at speedvid and most sites load from .net but the domains down right now. quick example
http://www.speedvid.net/l300u4avjxma
