### ISSUE TITLE
Rapidvideo only 720p

### ISSUE THREAD

**Issue by TheWizard67** [jsergio123/script.module.resolveurl#86]
Don't know if the problem is at my end, but if i send a link ending in &q=1080p to resolveurl it stil plays in 720p am i doing something wrong or is something broke?

**Comment by Gujal00** [comment]
Couldnt find any 1080p links at rapidvideo, almost everything seems to be 480p+720p

**Comment by jsergio123** [comment]
@gujal so no issue then?

**Comment by Gujal00** [comment]
720p plays fine, I could not find any 1080p embeds so cant test, otherwise no issue

**Comment by jewbmx** [comment]
123moviehd has a few. Just did a test on a 1080p and it worked fine. Rapid has been a bit glitchy the past month or but its all good.

**Comment by TheWizard67** [comment]
@jsergio123 @Gujal00 Here is one you can try feeding to it. 
https://www.rapidvideo.com/e/G0REE9YMW3&q=1080p

**Comment by Gujal00** [comment]
Yes, it is playing 1080p correctly as below
![image](https://i.imgur.com/WzVhvUa.png)

**Comment by TheWizard67** [comment]
@Gujal00 Strange, you are right. Last time i tried it always played 720p.
That being said its working now.
