### ISSUE TITLE
Streamplay not working

### ISSUE THREAD

**Issue by bjgood** [jsergio123/script.module.resolveurl#87]
Hi JSergio,
If you get a chance could you check out streamplay? It shows up a lot in an episode scan but never gives a working link (about like vidzi, which we discussed before :)).

Have a good day, and thanks for your hard work, bud.

Later...

**Comment by doko-desuka** [comment]
> `<script src="https://www.google.com/recaptcha/api.js" async defer></script><div class="g-recaptcha" data-sitekey="6LfwW48UAAAAAPOxDGJBARwBjEoVJX2YyXjj1ev_"></div>`

Streamplay is using a silent Google reCaptcha to tell if the visitor has Javascript enabled or not.  
The Python resolver doesn't use JS, so there's no way around it unfortunately.

**Comment by bjgood** [comment]
Thanks, dojo, for the explanation. I'll close it right now.

Thanks, buddy.
