### ISSUE TITLE
Thevid.net

### ISSUE THREAD

**Issue by antrrax** [jsergio123/script.module.resolveurl#88]
Please update thevid.net server.
In my country address thevid.net  is being blocked by internet providers. You could include thevid.tv address to the addon, it's the same site just changes the url.
thanks

**Comment by jsergio123** [comment]
Will do

**Comment by jsergio123** [comment]
added https://github.com/jsergio123/script.module.resolveurl/commit/c121a768ce8d7b9ac60e48dde77716ff8845ad14
