### ISSUE TITLE
Release Hub (Url Resolver Broken)

### ISSUE THREAD

**Issue by doser5** [jsergio123/script.module.resolveurl#9]
By any chance can you update release hub to use resolveurl instead of urlresolver. Release Hub debrid no longer works at all and i was wondering if you're able to push out a fix? MrEntertainment no longer maintains release hub as he deleted all his accounts, twitter, github etc.

**Comment by doser5** [comment]
Thanks in advanced and for all the hard work you do for the kodi community.

**Comment by jsergio123** [comment]
Sorry this is something I can not do.

**Comment by doser5** [comment]
What if i add resolveurl myself and you look over my code to make sure that implmentation i did for resolve url is right?

**Comment by doser5** [comment]
for "Entertainment Hub". I'll try add resolveurl and import the modules etc?

**Comment by jsergio123** [comment]
I don't believe so
