### ISSUE TITLE
New host stream.lewd.host

### ISSUE THREAD

**Issue by TheWizard67** [jsergio123/script.module.resolveurl#92]
Hello @jsergio123 could it be possible to add this host?
Example link:
https://stream.lewd.host/embed/M1fr8una57t48Wf/

Best regards.

**Comment by TheWizard67** [comment]
Thanks alot!

**Comment by tempadev1** [comment]
Hello j Sergio is possible to add this host pls
https://flix555.com/embed-c2inbg05bfqi.html

**Comment by jewbmx** [comment]
Flix555 is already there and working

**Comment by tempadev1** [comment]
Hello @jsergio123 is so possible to add this host link pls
https://flix555.com/embed-c2inbg05bfqi.html

**Comment by tempadev1** [comment]
On my side is not resolving

**Comment by tempadev1** [comment]
Pls help
