### ISSUE TITLE
DM links not resolving

### ISSUE THREAD

**Issue by pinoytracker** [jsergio123/script.module.resolveurl#93]
Hi Jsergio,
Stream UrlOpen Failed: Url: https://www.dailymotion.com/cdn/H264-848x480/video/x73m13a.mp4?sec=smiPT6HJ1sqiqPrGng8C1RFiLE7hRUtjDymuGrDPX0QUgYUd2C7-rQxHX399P8xIOV57qf_t-BDXvw1gpXhMGw|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A61.0%29+Gecko%2F20100101+Firefox%2F61.0 HTTP Code: 403 Msg: Forbidden (ENCODED)

sample link = https://www.dailymotion.com/embed/video/k37BTAp8zVDJ8Bt3qke?start=0&logo=0&info=0 

Thanks

**Comment by Gujal00** [comment]
This is tricky fix. The links are resolved correctly by the site plugin but SMR then tries to open the link before passing it to the addon and doesnt follow redirects with cookies presented. There is no need for SMR to open the link, @jsergio123 needs to look at this

**Comment by compyy** [comment]
it works with latest fix of dailymotion addon itself
