### ISSUE TITLE
Rapidvideo host no resuleve

### ISSUE THREAD

**Issue by Andorth** [jsergio123/script.module.resolveurl#98]
Hola Sergio en primer lugar darte las gracias por tu trabajo.
el servidor Rapidvideo falla. Pero este permite buscar la Source="" en la propia web.

Ejemplo:
    Para https://www.rapidvideo.com/v/FT42TGJ44S&q=1080p
buscamos: 
 Rapidvideo Source: 
<div id="home_video" style="width:100%;height:100%;">
--
  | <video id="videojs" name="videojs" class="video-js vjs-big-play-centered" controls preload="auto" poster="https://a07o544l1f.playercdn.net/thumb/0/180709/GSWhDfqE91JjpWU.jpg" style="width:100%; height:100%;"  data-setup=''>

**<source src="https://rgctsmbil1.playercdn.net/88/2/88fb05BmsuWZfp22_9wvxg/1553467438/180709/zEHYyxgqHyVN7iR.mp4" type="video/mp4" title="1080p" data-res="1080" />**

Devolviendo:
https://rgctsmbil1.playercdn.net/88/2/88fb05BmsuWZfp22_9wvxg/1553467438/180709/zEHYyxgqHyVN7iR.mp4

Gracias por tu trabajo, no se como ayudarte porque no se mucho de python, pero supongo que ha cambiado la estructura y no sera muy complicado actualizar esa seccion.

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.resolveurl/commit/466b87fad424f6580d20fca73572dbe86b9fa22e
